# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0.

# Mesh-level Prometheus metrics for Inherent client and server reporters.
apiVersion: telemetry.dubbo.apache.org/v1alpha3
kind: Telemetry
metadata:
  name: metrics-tags
  namespace: dubbo-system
spec:
  metrics:
  - providers:
    - name: prometheus
    rules:
    - metric: REQUEST_COUNT
      scope: CLIENT_AND_SERVER
      tags:
        grpc_response_status:
          action: REMOVE
