{{ $ingress := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-dashboard
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ $ingress.hosts.admin }}
    secretName: dubbo-kubernetes-ingress-tls
  ingressClassName: {{ $ingress.class |default "dubbo" }}
  rules:
  - host: {{ $ingress.hosts.admin | default "dubbo" }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: admin-dashboard
              port:
                number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-prometheus-prometheus
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ $ingress.hosts.prometheus }}
    secretName: dubbo-kubernetes-ingress-tls
  ingressClassName: {{ $ingress.class | default "dubbo" }}
  rules:
  - host: {{ $ingress.hosts.prometheus }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kube-prometheus-prometheus
              port:
                number: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ $ingress.hosts.grafana }}
    secretName: dubbo-kubernetes-ingress-tls
  ingressClassName: {{ $ingress.class | default "dubbo" }}
  rules:
  - host: {{ $ingress.hosts.grafana }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: grafana
              port:
                number: 80
