{{- if $.Values.defaults }}
{{ fail (cat
  "`--set defaults.foo=bar` with `--set foo=bar`. Defaults set:\n"
  ($.Values.defaults | toYaml |nindent 4) ) }}
{{- end }}
{{- $defaults := $.Values._internal_default_values_are_not_set }}
{{- $_ := unset $.Values "_internal_default_values_are_not_set " }}
{{- $profile := dict }}
{{- with (coalesce ($.Values).profile ($.Values.global).profile) }}
{{- with $.Files.Get (printf "files/profile-%s.yaml" .)}}
{{- $profile = (. | fromYaml) }}
{{- else }}
{{ fail (cat "unknown profile" .) }}
{{- end }}
{{- end }}
{{- if false }}
{{- $a := mustMergeOverwrite $defaults ($profile.global) ($.Values.global | default dict)  }}
{{- end }}
{{- $b := set $ "Values" (mustMergeOverwrite $defaults $.Values) }}
