# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

bug:
  - head-branch:
      - '^bug/'
      - '^bugfix/'
      - '^fix/'

feature:
  - head-branch:
      - '^feat/'
      - '^feature/'

dependencies:
  - any:
      - head-branch:
          - '^dependabot/'
      - changed-files:
          - any-glob-to-any-file:
              - '**/go.mod'
              - '**/go.sum'
              - '.github/dependabot.yml'

github_actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/actions/**'
          - '.github/workflows/**'

go:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.go'
          - '**/go.mod'
          - '**/go.sum'

python:
  - changed-files:
      - any-glob-to-any-file: '**/*.py'

cni:
  - changed-files:
      - any-glob-to-any-file:
          - 'cni/**'
          - 'pkg/cni/**'

dubboctl:
  - changed-files:
      - any-glob-to-any-file:
          - 'cli/**'
          - 'dubboctl/**'

dubbod:
  - changed-files:
      - any-glob-to-any-file: 'dubbod/**'

operator:
  - changed-files:
      - any-glob-to-any-file: 'operator/**'

helm:
  - changed-files:
      - any-glob-to-any-file: 'manifests/charts/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'site/**'

testing:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_test.go'
          - 'tests/**'

performance:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*benchmark*'
          - '**/benchmark/**'
          - '.github/workflows/benchmark.yml'

security:
  - changed-files:
      - any-glob-to-any-file:
          - '**/security/**'
          - 'tools/govulncheck.py'
          - '.github/workflows/security.yml'

networking:
  - changed-files:
      - any-glob-to-any-file:
          - 'dubbod/discovery/pkg/networking/**'
          - 'pkg/adsc/**'
          - 'pkg/xds/**'

samples:
  - changed-files:
      - any-glob-to-any-file: 'samples/**'

build:
  - changed-files:
      - any-glob-to-any-file:
          - 'Makefile'
          - 'tools/make/**'
          - 'tools/ci/**'
          - '**/Dockerfile*'
          - '**/dockerfile*'

release:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/release.yaml'
          - 'tools/release/**'
