{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled }}
apiVersion: {{ template "network.apiVersion" . }}
kind: IngressClass
metadata:
  name: {{ template "traefik.name" . }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  controller: traefik.io/ingress-controller
{{- end -}}
