{{- $jobs := .Values.jobs -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: jobs-env
  namespace: default
  labels:
    app.kubernetes.io/name: jobs
    helm.sh/chart: jobs-1.28.4
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
data:
  kubectl.sh: |-
    {{- .Files.Get "files/kubectl.sh" | nindent 4 }}
  helm.sh: |-
    {{- .Files.Get "files/helm.sh" | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-1
  namespace: default
  labels:
    app.kubernetes.io/name: jobs
    helm.sh/chart: jobs-1.28.4
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      name: jobs-1
      namespace: default
    spec:
      serviceAccountName: helm-job-sa
      restartPolicy: OnFailure
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 8.8.8.8
        searches:
        - default.svc.cluster.local
      containers:
      - name: kubectl
        image: {{ $jobs.image.registry }}:{{ $jobs.image.tag }}
        imagePullPolicy: {{ $jobs.image.pullPolicy }}
        command: [ "/bin/sh", "-c", "sh /files/kubectl.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /files/kubectl.sh
          subPath: kubectl.sh
      volumes:
      - name: scripts
        configMap:
          name: jobs-env
          defaultMode: 0755
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-2
  namespace: default
  labels:
    app.kubernetes.io/name: jobs
    helm.sh/chart: jobs-1.28.4
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      name: jobs-2
      namespace: default
    spec:
      serviceAccountName: helm-job-sa
      restartPolicy: OnFailure
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
        searches:
          - default.svc.cluster.local
      containers:
        - name: helm
          image: alpine/helm:3.16.2
          imagePullPolicy: {{ $jobs.image.pullPolicy }}
          command: ["/bin/sh", "-c", "sh /files/helm.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /files/helm.sh
              subPath: helm.sh
      volumes:
        - name: scripts
          configMap:
            name: jobs-env
            defaultMode: 0755
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-job-sa
  namespace: default
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-job-sa-binding
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm-job-sa
    namespace: default