{{- $jobs := .Values.jobs -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: extra-job-create
  namespace: {{ template "admin.namespace" . }}
  labels:
  {{- include "jobs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    metadata:
      name: extra-job-create
    spec:
      restartPolicy: {{ $jobs.restartPolicy }}
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 8.8.8.8
        searches:
        - default.svc.cluster.local
        - svc.cluster.local
        - cluster.local
      containers:
      - name: helm
        image: alpine/helm:3.16.2
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/sh"
        - "-c"
        - "sh /files/helm.sh"
        volumeMounts:
        - name: scripts
          mountPath: /files/helm.sh
          subPath: helm.sh
        - name: scripts
          mountPath: /files/resources/dubbo-metrics.yaml
          subPath: dubbo-metrics.yaml
      volumes:
      - name: scripts
        configMap:
          name: {{ include "job.name" . }}-config
          defaultMode: 0755