apiVersion: v1
kind: ConfigMap
metadata:
  name: my-script
data:
  env.sh: |-

    {{- .Files.Get "files/env.sh" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: run-external-script
spec:
  template:
    spec:
      containers:
        - name: script-runner
          image: alpine:latest  # 选择一个适合的基础镜像
          command: ["/bin/sh", "-c", "/scripts/env.sh"]
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: my-script
  backoffLimit: 4
