{{- $auth := .Values.auth -}}{{- $authz := $auth.authorization -}}{{- $authc := $auth.authentication -}}
{{- if $auth.enabled }}
apiVersion: dubbo.io/v1alpha1
kind: AuthenticationPolicy
metadata:
  name: admin-authentication
  namespace: {{ template "admin.namespace" . }}
spec:
  action: {{ $authc.action }}
  PortLevel:
    - port: {{ $authc.port }}
  selector:
    - namespaces: [{{ template "admin.namespace" . }}]
---
apiVersion: dubbo.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: admin-authorization
  namespace: {{ template "admin.namespace" . }}
spec:
  action: {{ $authz.action }}
  matchType: {{ $authz.matchType }}
  rules:
  - from:
      namespaces: [{{ template "admin.namespace" . }}]
  samples: {{ $authz.samples }}
{{- end }}

