apiVersion: v1
kind: ServiceAccount
metadata:
  name: dubbo-sa
  namespace: {{ template "admin.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dubbo-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dubbo-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dubbo-clusterrole
subjects:
  - kind: ServiceAccount
    name: dubbo-sa
    namespace: {{ template "admin.namespace" . }}