{
 "title": "application",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "application_name",
    "query": {
     "query": "label_values(dubbo_application_info_total{},application_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(dubbo_application_info_total{application_name=\"$application_name\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "应用概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "调用成功率（作为消费者）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(dubbo_consumer_requests_succeed_total{application_name=\"$application_name\"})   / sum(dubbo_consumer_requests_total{application_name=\"$application_name\"})  ) OR on() vector(NAN)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "被调用成功率（作为生产者）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (dubbo_provider_requests_succeed_total{application_name=\"$application_name\"}) / sum (dubbo_provider_requests_total{application_name=\"$application_name\"}) OR  vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(dubbo_provider_qps_total{application_name=\"$application_name\"})",
     "legendFormat": "生产者被调用"
    },
    {
     "expr": "sum(dubbo_consumer_qps_total{application_name=\"$application_name\"})",
     "legendFormat": "消费者调用"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_avg_milliseconds_aggregate{application_name=\"$application_name\"}>0)",
     "legendFormat": "调用 avg RT"
    },
    {
     "expr": "avg(dubbo_provider_rt_avg_milliseconds_aggregate{application_name=\"$application_name\"}>0)",
     "legendFormat": "被调用 avg RT"
    }
   ]
  },
  {
   "title": "并发",
   "type": "timeseries",
   "description": "当前正在处理的请求",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "dubbo_provider_requests_processing{application_name=\"$application_name\"} or vector(0)",
     "legendFormat": "生产者处理并发量"
    },
    {
     "expr": "dubbo_consumer_requests_processing{application_name=\"$application_name\"} or vector(0)",
     "legendFormat": "消费者调用并发量"
    }
   ]
  },
  {
   "title": "最近调用RT（作为生产者）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_milliseconds_last{application_name=\"$application_name\"})",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "调用总览(作为消费者 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_consumer_requests_total{application_name=\"$application_name\"}[2m])>0) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_succeed_total{application_name=\"$application_name\"}[2m])>0) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_failed_total{application_name=\"$application_name\"}[2m])>0) OR vector(0)",
     "legendFormat": "失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_business_failed_total{application_name=\"$application_name\"}[2m])>0)  OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_timeout_total{application_name=\"$application_name\"}[2m])>0) OR vector(0)",
     "legendFormat": "超时数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_unknown_failed_tota{application_name=\"$application_name\"}[2m])>0) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application_name\"}[2m])>0) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_network_total{application_name=\"$application_name\"}[2m])>0) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_codec_total{application_name=\"$application_name\"}[2m])>0) OR vector(0)",
     "legendFormat": "编解码错误数"
    }
   ]
  },
  {
   "title": "被调用总览(作为生产者 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_provider_requests_total{application_name=\"$application_name\"}[2m])) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_provider_requests_succeed_total{application_name=\"$application_name\"}[2m]) ) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_provider_requests_failed_total{application_name=\"$application_name\"}[2m]) ) OR vector(0)",
     "legendFormat": "失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_business_failed_total{application_name=\"$application_name\"}[2m])) OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_timeout_total{application_name=\"$application_name\"}[2m])) OR vector(0)",
     "legendFormat": "超时数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_unknown_failed_tota{application_name=\"$application_name\"}[2m])) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application_name\"}[2m])) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_network_total{application_name=\"$application_name\"}[2m])) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_codec_total{application_name=\"$application_name\"}[2m])) OR vector(0)",
     "legendFormat": "序列化错误数"
    }
   ]
  },
  {
   "title": "最近调用RT（作为消费者）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_milliseconds_last{application_name=\"$application_name\"})",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "QPS (生产者 & 消费者)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "被调用QPS（作为生产者）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "avg(sum(dubbo_provider_qps_total{application_name=\"$application_name\"}) by (instance))",
       "legendFormat": "平均QPS"
      },
      {
       "expr": "sum(dubbo_provider_qps_total{application_name=\"$application_name\"}) by (instance, pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "调用QPS（作为消费者）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "avg(sum(dubbo_consumer_qps_total{application_name=\"$application_name\"}) by (instance))",
       "legendFormat": "平均QPS"
      },
      {
       "expr": "sum(dubbo_consumer_qps_total{application_name=\"$application_name\"}) by (instance, pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "应用调用详情（作为消费者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "调用总数(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_total{application_name=\"$application_name\"}[2m])>0)",
       "legendFormat": "总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_total{application_name=\"$application_name\"}[2m])>0) by (instance,pod) ",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "调用成功(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 37 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_succeed_total{application_name=\"$application_name\"}[2m])>0) ",
       "legendFormat": "成功总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_succeed_total{application_name=\"$application_name\"}[2m])>0) by (instance,pod) ",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "调用失败(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 37 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_total{application_name=\"$application_name\"}[2m])>0) ",
       "legendFormat": "失败总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_total{application_name=\"$application_name\"}[2m])>0) by (instance,pod) ",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "业务原因错误(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_business_failed_total{application_name=\"$application_name\"}[2m]))",
       "legendFormat": "业务原因错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_business_failed_total{application_name=\"$application_name\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "超时错误(Consumer 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 47 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_timeout_total{application_name=\"$application_name\"}[2m])) ",
       "legendFormat": "超时错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_timeout_total{application_name=\"$application_name\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 47 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application_name\"}[2m])) >0",
       "legendFormat": "服务不可用总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application_name\"}[2m])) by (instance,pod) >0",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "网络错误(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_network_total{application_name=\"$application_name\"}[2m])) ",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_network_total{application_name=\"$application_name\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "序列化错误(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 57 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_codec_total{application_name=\"$application_name\"}[2m])) ",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_codec_total{application_name=\"$application_name\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "未知原因错误(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 57 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_unknown_failed_tota{application_name=\"$application_name\"}[2m])) >0",
       "legendFormat": "未知原因失败总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_unknown_failed_total{application_name=\"$application_name\"}[2m])) by (instance,pod)>0",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "应用被调用详情（作为生产者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "被调用总数(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_total{application_name=\"$application_name\"}[2m])) >0",
       "legendFormat": "总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_total{application_name=\"$application_name\"}[2m])) by (instance,pod)>0",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "被调用成功(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_succeed_total{application_name=\"$application_name\"}[2m])) >0",
       "legendFormat": "成功数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_succeed_total{application_name=\"$application_name\"}[2m])) by (instance,pod)>0",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "被调用失败(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_total{application_name=\"$application_name\"}[2m]))>0",
       "legendFormat": "失败总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_total{application_name=\"$application_name\"}[2m])) by (instance,pod)>0",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "业务原因错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_business_failed_total{application_name=\"$application_name\"}[2m]))>0",
       "legendFormat": "业务原因错误总数"
      },
      {
       "expr": "sum(increase (dubbo_provider_requests_business_failed_total{application_name=\"$application_name\"} [2m]) )by(instance,pod)>0\r\n",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "超时错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_timeout_total{application_name=\"$application_name\"}[2m]))",
       "legendFormat": "超时总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_timeout_total{application_name=\"$application_name\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 31 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application_name\"}[2m]))",
       "legendFormat": "服务不可用总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application_name\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "网络错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_network_total{application_name=\"$application_name\"}[2m]))>0",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum(label_replace(increase(dubbo_provider_requests_failed_network_total{application_name=\"$application_name\"}[2m]), \"instance\", \"$1\", \"instance\", \"(.*):.*\")) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "序列化错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 41 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_codec_total{application_name=\"$application_name\"}[2m])) >0",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_codec_total{application_name=\"$application_name\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "未知原因错误(作为生产者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 41 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_unknown_failed_total{application_name=\"$application_name\"}[2m])) >0",
       "legendFormat": "未知原因失败总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_unknown_failed_total{application_name=\"$application_name\"}[2m])) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "应用请求时延RT (Consumer)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "调用 RT P95(作为消费者)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_consumer_rt_milliseconds_p95{application_name=\"$application_name\",}>0) by(instance,pod)",
       "legendFormat": "{{instance}}_{pod}"
      }
     ]
    },
    {
     "title": "调用 RT P99(作为消费者)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_consumer_rt_milliseconds_p99{application_name=\"$application_name\",}>0) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "应用响应时延RT (Provider)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "RT P95(作为生产者)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_provider_rt_milliseconds_p95{application_name=\"$application_name\",}>0) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    },
    {
     "title": "响应平均时延 P99(Provider)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_provider_rt_milliseconds_p99{application_name=\"$application_name\",}>0) by (instance,pod)",
       "legendFormat": "{{instance}}_{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "注册中心",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "注册实例次数",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(dubbo_registry_register_requests_total{application_name=\"$application_name\"})",
       "legendFormat": "注册总次数"
      },
      {
       "expr": "sum(dubbo_registry_register_requests_succeed_total{application_name=\"$application_name\"})OR on() vector(0)",
       "legendFormat": "注册成功数"
      },
      {
       "expr": "sum(dubbo_registry_register_requests_failed_total{application_name=\"$application_name\"})  OR on() vector(0)",
       "legendFormat": "注册失败数"
      }
     ]
    },
    {
     "title": "实例注册时长",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "dubbo_register_rt_milliseconds_sum{application_name=\"$application_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "deprecated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "实例",
     "type": "table",
     "description": "只有启动成功的实例并接入监控的才会显示",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 139 },
     "targets": [
      {
       "expr": "count (dubbo_application_info_total{application_name=\"$application_name\"}) by(application_name,instance,application_version,host,pod,clusterName)",
       "legendFormat": "实例总数"
      }
     ]
    },
    {
     "title": "提供接口",
     "type": "table",
     "description": "有请求的接口才会展示",
     "gridPos": { "h": 7, "w": 7, "x": 10, "y": 139 },
     "targets": [
      {
       "expr": "count by(interface,version) (dubbo_provider_requests_total{application_name=\"$application_name\",interface!~\"org.apache.dubbo.metrics.service.MetricsService|org.apache.dubbo.metadata.MetadataService\"})"
      }
     ]
    },
    {
     "title": "消费接口",
     "type": "table",
     "description": "有请求的接口才会展示",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 139 },
     "targets": [
      {
       "expr": "count by(interface,version) (dubbo_consumer_requests_total{application_name=\"$application_name\",interface!~\"org.apache.dubbo.metrics.service.MetricsService|org.apache.dubbo.metadata.MetadataService\"})"
      }
     ]
    },
    {
     "title": "实例版本分布",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 146 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(application_version)(dubbo_application_info_total{application_name=\"$application_name\",instance=~\".*\"})",
       "legendFormat": "{{application_version}}"
      }
     ]
    },
    {
     "title": "提供接口数",
     "type": "stat",
     "description": "准确的提供接口数量",
     "gridPos": { "h": 5, "w": 3, "x": 2, "y": 146 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by(interface) (dubbo_provider_requests_total{application_name=\"$application_name\",interface!~\"org.apache.dubbo.metrics.service.MetricsService|org.apache.dubbo.metadata.MetadataService\"}))"
      }
     ]
    },
    {
     "title": "消费接口数",
     "type": "stat",
     "description": "准确的提供接口数量",
     "gridPos": { "h": 5, "w": 3, "x": 5, "y": 146 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by(interface) (dubbo_consumer_requests_total{application_name=\"$application_name\",interface!~\"org.apache.dubbo.metrics.service.MetricsService|org.apache.dubbo.metadata.MetadataService\"}))"
      }
     ]
    },
    {
     "title": "响应时延热点图 (Provider)",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 151 },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(dubbo_provider_rt_milliseconds_histogram_seconds_bucket{application_name=\"$application_name\",method=\"getItem\"}[2m])) by (le))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}