{
 "title": "instance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "application",
    "query": {
     "query": "label_values(dubbo_application_info_total{},application_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(dubbo_application_info_total{application_name=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "实例概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "调用成功率（作为消费者）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(dubbo_consumer_requests_succeed_total{application_name=\"$application\",instance=\"$instance\"})   / sum(dubbo_consumer_requests_total{application_name=\"$application\",instance=\"$instance\"})  ) OR on() vector(NAN)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "被调用成功率（作为生产者）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (dubbo_provider_requests_succeed_total{application_name=\"$application\",instance=\"$instance\"}) / sum (dubbo_provider_requests_total{application_name=\"$application\",instance=\"$instance\"}) OR  vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(dubbo_provider_qps_total{application_name=\"$application\",instance=\"$instance\"})",
     "legendFormat": "提供端QPS"
    },
    {
     "expr": "sum(dubbo_consumer_qps_total{application_name=\"$application\",instance=\"$instance\"})",
     "legendFormat": "消费者QPS"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_avg_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0)",
     "legendFormat": "消费者RT"
    },
    {
     "expr": "avg(dubbo_provider_rt_avg_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0)",
     "legendFormat": "提供端RT"
    }
   ]
  },
  {
   "title": "并发",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum (dubbo_provider_requests_processing{instance=\"$instance\"} ) OR vector (0)",
     "legendFormat": "生产者处理并发量"
    },
    {
     "expr": "sum(dubbo_consumer_requests_processing{instance=\"$instance\"}) OR vector (0)",
     "legendFormat": "消费者调用并发量"
    }
   ]
  },
  {
   "title": "最近被调用RT（作为生产者）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dubbo_provider_rt_milliseconds_last{application_name=\"$application\",instance=\"$instance\"}",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "实例调用(作为消费者 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_consumer_requests_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_succeed_total{application_name=\"$application\",instance=\"$instance\"}[2m]) ) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_failed_total{application_name=\"$application\",instance=\"$instance\"}[2m]) ) OR vector(0)",
     "legendFormat": "失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_timeout_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "请求超时数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_unknown_failed_tota{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_network_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_codec_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "序列化错误数"
    }
   ]
  },
  {
   "title": "实例被调用(作为生产者 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_provider_requests_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_provider_requests_succeed_total{application_name=\"$application\",instance=\"$instance\"}[2m]) ) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_provider_requests_failed_total{application_name=\"$application\",instance=\"$instance\"}[2m]) ) OR vector(0)",
     "legendFormat": "失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_timeout_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "超时数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_unknown_failed_tota{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\"}[2m])) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_network_total{application_name=\"$application\"}[2m])) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_provider_requests_failed_codec_total{application_name=\"$application\"}[2m])) OR vector(0)",
     "legendFormat": "序列化错误数"
    }
   ]
  },
  {
   "title": "最近调用时延（作为消费者）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dubbo_consumer_rt_milliseconds_last{application_name=\"$application\",instance=\"$instance\"}",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "实例QPS 详情（生产者&消费者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "提供接口QPS（作为生产者）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(dubbo_provider_qps_total{application_name=\"$application\",instance=\"$instance\",}) by (interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "依赖接口QPS（作为消费者）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(dubbo_consumer_qps_total{application_name=\"$application\",instance=\"$instance\",}) by (interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "实例被调用详情（作为生产者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求总数(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "请求总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "请求成功(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_succeed_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "请求成功总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_succeed_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "请求失败(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "请求失败总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "业务原因错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) or vector(0)",
       "legendFormat": "业务原因错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "超时错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_timeout_total{application_name=\"$application\",instance=\"$instance\",}[2m]))  or vector(0)",
       "legendFormat": "超时错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_timeout_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "服务不可用错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "网络错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_network_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_network_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)  ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "序列化错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_codec_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_codec_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)  ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "未知原因错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_unknown_failed_tota{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "未知原因错误总数"
      },
      {
       "expr": "sum (increase(dubbo_provider_requests_unknown_failed_tota{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "实例调用详情（作为消费者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "调用总数(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "调用总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "调用成功(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_succeed_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "调用成功总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_succeed_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "调用失败(作为消费者 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_total{instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "调用失败总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_total{instance=\"$instance\",}[2m])) by (interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "业务原因错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "业务原因错误"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_business_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "超时错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_timeout_total{application_name=\"$application\",instance=\"$instance\",}[2m]))  or vector(0)",
       "legendFormat": "超时错误"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_timeout_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "服务不可用"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_service_unavailable_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "网络错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_network_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_network_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface)",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "序列化错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_codec_total{application_name=\"$application\",instance=\"$instance\",}[2m])) or vector(0)",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_codec_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "未知原因错误(2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_unknown_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) or vector(0)",
       "legendFormat": "未知原因错误"
      },
      {
       "expr": "sum (increase(dubbo_consumer_requests_unknown_failed_total{application_name=\"$application\",instance=\"$instance\",}[2m])) by(interface) ",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "实例 RT 详情(作为生产者)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "RT P95",
     "type": "timeseries",
     "description": "作为生产者，响应上游服务的95%的请求的RT",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_provider_rt_milliseconds_p95{application_name=\"$application\",instance=\"$instance\",}>0)",
       "legendFormat": "avgRT P95 "
      },
      {
       "expr": "dubbo_provider_rt_milliseconds_p95{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}.{{method}} P95 RT"
      }
     ]
    },
    {
     "title": "RT P99",
     "type": "timeseries",
     "description": "作为生产者，响应上游服务的99%的请求的RT",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_provider_rt_milliseconds_p99{application_name=\"$application\",instance=\"$instance\",}>0)",
       "legendFormat": "avgRT P99"
      },
      {
       "expr": "dubbo_provider_rt_milliseconds_p99{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}.{{method}} P99 RT"
      }
     ]
    },
    {
     "title": "min RT",
     "type": "timeseries",
     "description": "作为生产者，响应上游服务请求的最小RT",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_min_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    },
    {
     "title": "max RT",
     "type": "timeseries",
     "description": "作为生产者，响应上游服务请求的最大RT",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_provider_rt_min_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}.{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "实例 RT 详情 (作为消费者)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "RT P95",
     "type": "timeseries",
     "description": "作为消费者，调用下游服务时95%的请求的RT",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_milliseconds_p95{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "RT P99(Consumer)",
     "type": "timeseries",
     "description": "作为消费者，调用下游服务时99%的请求的RT",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(dubbo_consumer_rt_milliseconds_p99{application_name=\"$application\",instance=\"$instance\",}>0)",
       "legendFormat": "avgRT P99"
      },
      {
       "expr": "dubbo_consumer_rt_milliseconds_p99{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "min RT ",
     "type": "timeseries",
     "description": "作为消费者，调用下游服务的最小RT",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_min_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "max RT",
     "type": "timeseries",
     "description": "作为消费者，调用下游服务的最大RT",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "dubbo_consumer_rt_max_milliseconds_aggregate{application_name=\"$application\",instance=\"$instance\",}>0",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dubbo线程池",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "线程池核心",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_core_size{application_name=\"$application\",instance=\"$instance\",thread_pool_name!~\".*MetadataService.*|.*MetricsService.*\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "线程池活跃",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_active_size{application_name=\"$application\",instance=\"$instance\",thread_pool_name!~\".*MetadataService.*|.*MetricsService.*\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "线程池队列",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_queue_size{application_name=\"$application\",instance=\"$instance\",thread_pool_name!~\".*MetadataService.*|.*MetricsService.*\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    },
    {
     "title": "线程池最大",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "dubbo_thread_pool_largest_size{application_name=\"$application\",instance=\"$instance\",thread_pool_name!~\".*MetadataService.*|.*MetricsService.*\"}",
       "legendFormat": "{{thread_pool_name}}"
      }
     ]
    }
   ]
  }
 ]
}