{
 "title": "service",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(dubbo_provider_requests_total{},interface)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(dubbo_provider_requests_total{interface=\"$service\"},method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "接口总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "调用成功率（Consumer）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(dubbo_consumer_requests_succeed_total{interface=\"$service\",method=~\"$method\"})   / sum(dubbo_consumer_requests_total{interface=\"$service\",method=~\"$method\"})  ) OR on() vector(NAN)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "被调用成功率（Provider）",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(dubbo_provider_requests_succeed_total{interface=\"$service\",method=~\"$method\"})   / sum(dubbo_provider_requests_total{interface=\"$service\",method=~\"$method\"})  ) OR on() vector(NAN)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(dubbo_consumer_qps_total{interface=\"$service\",method=~\"$method\"})",
     "legendFormat": "调用（消费者视角）"
    },
    {
     "expr": "sum(dubbo_provider_qps_total{interface=\"$service\",method=~\"$method\"})",
     "legendFormat": "被调用（生产者视角）"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_avg_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0)",
     "legendFormat": "调用 avg RT"
    },
    {
     "expr": "avg(dubbo_provider_rt_avg_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0)",
     "legendFormat": "被调用 avg RT"
    }
   ]
  },
  {
   "title": "并发",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum (dubbo_provider_requests_processing{interface=\"$service\"} ) OR vector (0)",
     "legendFormat": "生产者处理并发量"
    },
    {
     "expr": "sum(dubbo_consumer_requests_processing{interface=\"$service\"}) OR vector (0)",
     "legendFormat": "消费者调用并发量"
    }
   ]
  },
  {
   "title": "最近被调用时延（RT）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_milliseconds_last{interface=\"$service\",method=~\"$method\"})",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "被调用总览(生产者视角 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_provider_requests_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_provider_requests_succeed_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_failed_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "请求失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_business_failed_total{interface=\"$service\"}[2m])>0)  OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_timeout_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "超时数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_unknown_failed_tota{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_service_unavailable_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_network_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_codec_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "序列化错误数"
    }
   ]
  },
  {
   "title": "调用总览(消费者视角 2min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "sum (increase(dubbo_consumer_requests_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "总数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_succeed_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "成功数"
    },
    {
     "expr": "sum(increase(dubbo_consumer_requests_failed_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "请求失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_business_failed_total{interface=\"$service\"}[2m])>0)  OR vector(0)",
     "legendFormat": "业务原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_timeout_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "超时数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_unknown_failed_tota{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "未知原因失败数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_service_unavailable_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "服务不可用数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_network_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "网络错误数"
    },
    {
     "expr": "sum(increase (dubbo_consumer_requests_failed_codec_total{interface=\"$service\"}[2m])>0) OR vector(0)",
     "legendFormat": "编解码错误数"
    }
   ]
  },
  {
   "title": "最近调用时延（RT）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_milliseconds_last{interface=\"$service\",method=~\"$method\"})",
     "legendFormat": "实时时延"
    }
   ]
  },
  {
   "title": "接口QPS详情（生产者&消费者）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "被调用QPS （生产者视角）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(dubbo_provider_qps_total{interface=\"$service\"}) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "调用QPS（消费者视角）",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(dubbo_consumer_qps_total{interface=\"$service\"}) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "接口被调用详情（生产者详情）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求总数(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "请求总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求成功(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_succeed_total{interface=\"$service\"}[2m])) or vector(0) ",
       "legendFormat": "请求成功总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_succeed_total{interface=\"$service\",method=~\"$method\"}[2m])>0) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求失败(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "请求失败数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_total{interface=\"$service\",method=~\"$method\"}[2m])>0) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "业务原因错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_business_failed_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "业务原因错误总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_business_failed_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求超时错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_timeout_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "请求超时总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_timeout_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_service_unavailable_total{interface=\"$service\"}[2m])) ",
       "legendFormat": "服务不可用总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_service_unavailable_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "网络错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_network_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_network_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "序列化错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_failed_codec_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_failed_codec_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "未知原因错误(生产者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_provider_requests_unknown_failed_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "未知原因失败总数"
      },
      {
       "expr": "sum(increase(dubbo_provider_requests_unknown_failed_total{interface=\"$service\",method=~\"method\"}[2m])) by (mehtod)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "接口调用详情（消费者视角）",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "请求总数(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "请求总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求成功(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_succeed_total{interface=\"$service\"}[2m])) or vector(0) ",
       "legendFormat": "请求成功数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_succeed_total{interface=\"$service\",method=~\"$method\"}[2m])>0) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求失败(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "请求失败数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_total{interface=\"$service\",method=~\"$method\"}[2m])>0) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "业务原因错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_business_failed_total{interface=\"$service\"}[2m])) or vector(0)",
       "legendFormat": "业务原因错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_business_failed_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "请求超时错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_timeout_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "请求超时总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_timeout_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "服务不可用错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_service_unavailable_total{interface=\"$service\"}[2m])) ",
       "legendFormat": "服务不可用总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_service_unavailable_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method) ",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "网络错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_network_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "网络错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_network_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "序列化错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_failed_codec_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "序列化错误总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_failed_codec_total{interface=\"$service\",method=~\"$method\"}[2m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "未知原因错误(消费者视角 2min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "expr": "sum (increase(dubbo_consumer_requests_unknown_failed_total{interface=\"$service\"}[2m])) OR vector(0)",
       "legendFormat": "未知原因失败总数"
      },
      {
       "expr": "sum(increase(dubbo_consumer_requests_unknown_failed_total{interface=\"$service\",method=~\"method\"}[2m])) by (mehtod)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  { "title": "接口RT详情（生产者视角）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "RT P95",
   "type": "timeseries",
   "description": "生产者响应 此接口的95%请求的RT",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_milliseconds_p95{interface=\"$service\",method=~\"$method\"}>0) by (method) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RT P99",
   "type": "timeseries",
   "description": "生产者响应 此接口的99%请求的RT",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_milliseconds_p99{interface=\"$service\",method=~\"$method\"}>0) by (method) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "min RT",
   "type": "timeseries",
   "description": "生产者响应此接口请求的最小RT",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_min_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": " max RT",
   "type": "timeseries",
   "description": "生产者响应此接口请求的最大RT",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_provider_rt_max_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "接口 RT详情（消费者视角）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "RT P95",
   "type": "timeseries",
   "description": "消费者调用此接口时95%的请求的RT",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_milliseconds_p95{interface=\"$service\",method=~\"$method\"}>0) by (method) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RT P99",
   "type": "timeseries",
   "description": "消费者调用此接口时99%的请求的RT",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_milliseconds_p99{interface=\"$service\",method=~\"$method\"}>0) by (method) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "min RT",
   "type": "timeseries",
   "description": "消费者调用此接口的最小RT",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_min_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "max RT",
   "type": "timeseries",
   "description": "消费者调用此接口最大RT",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dubbo_consumer_rt_max_milliseconds_aggregate{interface=\"$service\",method=~\"$method\"}>0) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "deprecated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "接口方法",
     "type": "table",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "count by(method) (dubbo_provider_requests_total{interface=\"$service\"})"
      }
     ]
    }
   ]
  }
 ]
}