// Code generated by pkg/config/schema/codegen/tools/collections.main.go. DO NOT EDIT.

package kind

const (
	Unknown Kind = iota
	Address
	AuthorizationPolicy
	BackendTLSPolicy
	CircuitBreakerPolicy
	ConfigMap
	CustomResourceDefinition
	DNSName
	DaemonSet
	Deployment
	EndpointSlice
	Endpoints
	GatewayClass
	HTTPRoute
	HorizontalPodAutoscaler
	KubernetesGateway
	Lease
	MeshConfig
	MutatingWebhookConfiguration
	Namespace
	Node
	PeerAuthentication
	Pod
	PodDisruptionBudget
	ReferenceGrant
	RequestAuthentication
	Secret
	Service
	ServiceAccount
	ServiceEntry
	StatefulSet
	Telemetry
	ValidatingWebhookConfiguration
	WorkloadEntry
)

func (k Kind) String() string {
	switch k {
	case Address:
		return "Address"
	case AuthorizationPolicy:
		return "AuthorizationPolicy"
	case BackendTLSPolicy:
		return "BackendTLSPolicy"
	case CircuitBreakerPolicy:
		return "CircuitBreakerPolicy"
	case ConfigMap:
		return "ConfigMap"
	case CustomResourceDefinition:
		return "CustomResourceDefinition"
	case DNSName:
		return "DNSName"
	case DaemonSet:
		return "DaemonSet"
	case Deployment:
		return "Deployment"
	case EndpointSlice:
		return "EndpointSlice"
	case Endpoints:
		return "Endpoints"
	case GatewayClass:
		return "GatewayClass"
	case HTTPRoute:
		return "HTTPRoute"
	case HorizontalPodAutoscaler:
		return "HorizontalPodAutoscaler"
	case KubernetesGateway:
		return "KubernetesGateway"
	case Lease:
		return "Lease"
	case MeshConfig:
		return "MeshConfig"
	case MutatingWebhookConfiguration:
		return "MutatingWebhookConfiguration"
	case Namespace:
		return "Namespace"
	case Node:
		return "Node"
	case PeerAuthentication:
		return "PeerAuthentication"
	case Pod:
		return "Pod"
	case PodDisruptionBudget:
		return "PodDisruptionBudget"
	case ReferenceGrant:
		return "ReferenceGrant"
	case RequestAuthentication:
		return "RequestAuthentication"
	case Secret:
		return "Secret"
	case Service:
		return "Service"
	case ServiceAccount:
		return "ServiceAccount"
	case ServiceEntry:
		return "ServiceEntry"
	case StatefulSet:
		return "StatefulSet"
	case Telemetry:
		return "Telemetry"
	case ValidatingWebhookConfiguration:
		return "ValidatingWebhookConfiguration"
	case WorkloadEntry:
		return "WorkloadEntry"
	default:
		return "Unknown"
	}
}

func FromString(s string) Kind {
	switch s {
	case "Address":
		return Address
	case "AuthorizationPolicy":
		return AuthorizationPolicy
	case "BackendTLSPolicy":
		return BackendTLSPolicy
	case "CircuitBreakerPolicy":
		return CircuitBreakerPolicy
	case "ConfigMap":
		return ConfigMap
	case "CustomResourceDefinition":
		return CustomResourceDefinition
	case "DNSName":
		return DNSName
	case "DaemonSet":
		return DaemonSet
	case "Deployment":
		return Deployment
	case "EndpointSlice":
		return EndpointSlice
	case "Endpoints":
		return Endpoints
	case "GatewayClass":
		return GatewayClass
	case "HTTPRoute":
		return HTTPRoute
	case "HorizontalPodAutoscaler":
		return HorizontalPodAutoscaler
	case "KubernetesGateway":
		return KubernetesGateway
	case "Lease":
		return Lease
	case "MeshConfig":
		return MeshConfig
	case "MutatingWebhookConfiguration":
		return MutatingWebhookConfiguration
	case "Namespace":
		return Namespace
	case "Node":
		return Node
	case "PeerAuthentication":
		return PeerAuthentication
	case "Pod":
		return Pod
	case "PodDisruptionBudget":
		return PodDisruptionBudget
	case "ReferenceGrant":
		return ReferenceGrant
	case "RequestAuthentication":
		return RequestAuthentication
	case "Secret":
		return Secret
	case "Service":
		return Service
	case "ServiceAccount":
		return ServiceAccount
	case "ServiceEntry":
		return ServiceEntry
	case "StatefulSet":
		return StatefulSet
	case "Telemetry":
		return Telemetry
	case "ValidatingWebhookConfiguration":
		return ValidatingWebhookConfiguration
	case "WorkloadEntry":
		return WorkloadEntry
	default:
		return Unknown
	}
}
