# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbod
  namespace: dubbo-system
  labels:
    app: dubbod
    dubbo.apache.org/rev: default
spec:
  selector:
    matchLabels:
      app: dubbod
  template:
    metadata:
      labels:
        app: dubbod
    spec:
      serviceAccountName: dubbod
      containers:
        - name: discovery
          image: "kdubbo/dubbod:debug"
          imagePullPolicy: Always
          args:
            - "discovery"
            - --domain
            - cluster.local
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http-debug
            - containerPort: 26080
              protocol: TCP
              name: gui
            - containerPort: 26010
              protocol: TCP
              name: grpc-xds
            - containerPort: 26012
              protocol: TCP
              name: tls-xds
            - containerPort: 26017
              protocol: TCP
              name: https-webhooks
          env:
            - name: REVISION
              value: default
            - name: DUBBO_CERT_PROVIDER
              value: dubbod
            - name: CLUSTER_ID
              value: "Kubernetes"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
          resources:
            requests:
              cpu: 500m
              memory: 2048Mi
          volumeMounts:
          - mountPath: /var/run/secrets/dubbod/ca
            name: dubbo-csr-ca-configmap
            readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          name: dubbo-ca-root-cert
          optional: true
        name: dubbo-csr-ca-configmap
