{{- $auth := .Values.auth -}}{{- $authz := $auth.authorization -}}{{- $authc := $auth.authentication -}}
{{- if $auth.enabled }}
apiVersion: dubbo.io/v1alpha1
kind: AuthenticationPolicy
metadata:
  name: {{ template "cp.name" . }}-authentication
  namespace: {{ template "admin.namespace" . }}
spec:
  action: {{ $authc.action }}
  PortLevel:
    - port: {{ $authc.port }}
  selector:
    - namespaces: ["dubbo-system"]
---
apiVersion: dubbo.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: {{ template "cp.name" . }}-authorization
  namespace: {{ template "admin.namespace" . }}
spec:
  action: {{ $authz.action }}
  matchType: {{ $authz.matchType }}
  rules:
  - from:
      namespaces: ["dubbo-system"]
  samples: {{ $authz.samples }}
{{- end }}

