type: object
properties:
  type:
    description: 'the type of the resource'
    type: string
  mesh:
    description: 'Mesh is the name of the Dubbo mesh this resource belongs to.
      It may be omitted for cluster-scoped resources.'
    type: string
    default: default
  name:
    description: 'Name of the Dubbo resource'
    type: string
  spec: {}
