// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Regenerate with:
//
//   protoc -I . --go_out=. --go_opt=paths=source_relative \
//     --go-grpc_out=. --go-grpc_opt=paths=source_relative demand.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.0
// source: demand.proto

package demandpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActivationDemand_Report_FullMethodName = "/dubbo.activation.v1alpha1.ActivationDemand/Report"
)

// ActivationDemandClient is the client API for ActivationDemand service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ActivationDemand carries the requests a gateway is holding for Services that
// have no endpoints, so the control plane can tell KEDA to start them.
//
// A gateway must report to every control-plane replica, not just one. KEDA
// opens its activation stream against a single replica chosen by the Service,
// and a report that only reached a different replica would leave those requests
// waiting for a scale-up nobody asked for. Reports are idempotent snapshots
// precisely so broadcasting them is safe.
type ActivationDemandClient interface {
	// Report streams demand snapshots for the lifetime of the gateway.
	//
	// The stream itself is the liveness signal: when it ends, the control plane
	// drops that gateway's demand immediately instead of waiting for it to age
	// out, so a gateway that shuts down cleanly cannot hold a workload up.
	Report(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DemandSnapshot, ReportSummary], error)
}

type activationDemandClient struct {
	cc grpc.ClientConnInterface
}

func NewActivationDemandClient(cc grpc.ClientConnInterface) ActivationDemandClient {
	return &activationDemandClient{cc}
}

func (c *activationDemandClient) Report(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DemandSnapshot, ReportSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ActivationDemand_ServiceDesc.Streams[0], ActivationDemand_Report_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DemandSnapshot, ReportSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActivationDemand_ReportClient = grpc.ClientStreamingClient[DemandSnapshot, ReportSummary]

// ActivationDemandServer is the server API for ActivationDemand service.
// All implementations must embed UnimplementedActivationDemandServer
// for forward compatibility.
//
// ActivationDemand carries the requests a gateway is holding for Services that
// have no endpoints, so the control plane can tell KEDA to start them.
//
// A gateway must report to every control-plane replica, not just one. KEDA
// opens its activation stream against a single replica chosen by the Service,
// and a report that only reached a different replica would leave those requests
// waiting for a scale-up nobody asked for. Reports are idempotent snapshots
// precisely so broadcasting them is safe.
type ActivationDemandServer interface {
	// Report streams demand snapshots for the lifetime of the gateway.
	//
	// The stream itself is the liveness signal: when it ends, the control plane
	// drops that gateway's demand immediately instead of waiting for it to age
	// out, so a gateway that shuts down cleanly cannot hold a workload up.
	Report(grpc.ClientStreamingServer[DemandSnapshot, ReportSummary]) error
	mustEmbedUnimplementedActivationDemandServer()
}

// UnimplementedActivationDemandServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivationDemandServer struct{}

func (UnimplementedActivationDemandServer) Report(grpc.ClientStreamingServer[DemandSnapshot, ReportSummary]) error {
	return status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedActivationDemandServer) mustEmbedUnimplementedActivationDemandServer() {}
func (UnimplementedActivationDemandServer) testEmbeddedByValue()                          {}

// UnsafeActivationDemandServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivationDemandServer will
// result in compilation errors.
type UnsafeActivationDemandServer interface {
	mustEmbedUnimplementedActivationDemandServer()
}

func RegisterActivationDemandServer(s grpc.ServiceRegistrar, srv ActivationDemandServer) {
	// If the following call panics, it indicates UnimplementedActivationDemandServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivationDemand_ServiceDesc, srv)
}

func _ActivationDemand_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ActivationDemandServer).Report(&grpc.GenericServerStream[DemandSnapshot, ReportSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActivationDemand_ReportServer = grpc.ClientStreamingServer[DemandSnapshot, ReportSummary]

// ActivationDemand_ServiceDesc is the grpc.ServiceDesc for ActivationDemand service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivationDemand_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dubbo.activation.v1alpha1.ActivationDemand",
	HandlerType: (*ActivationDemandServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _ActivationDemand_Report_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "demand.proto",
}
