// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Regenerate with:
//
//   protoc -I . --go_out=. --go_opt=paths=source_relative \
//     --go-grpc_out=. --go-grpc_opt=paths=source_relative demand.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: demand.proto

package demandpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DemandSnapshot is the complete set of targets one gateway is holding
// requests for. It replaces that gateway's previous snapshot rather than
// adding to it, which is what lets a lost or duplicated message converge on
// the next send instead of skewing the total permanently.
type DemandSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identity of the reporting gateway, unique across replicas. Pod name
	// is the expected value; two gateways sharing an identity would overwrite
	// each other's counts.
	Reporter string `protobuf:"bytes,1,opt,name=reporter,proto3" json:"reporter,omitempty"`
	// Targets with requests waiting. A target absent from a snapshot has no
	// pending requests at that gateway; there is no separate clear message.
	Targets       []*TargetDemand `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandSnapshot) Reset() {
	*x = DemandSnapshot{}
	mi := &file_demand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandSnapshot) ProtoMessage() {}

func (x *DemandSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_demand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandSnapshot.ProtoReflect.Descriptor instead.
func (*DemandSnapshot) Descriptor() ([]byte, []int) {
	return file_demand_proto_rawDescGZIP(), []int{0}
}

func (x *DemandSnapshot) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *DemandSnapshot) GetTargets() []*TargetDemand {
	if x != nil {
		return x.Targets
	}
	return nil
}

type TargetDemand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace of the Service being activated.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Name of the Service being activated.
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// Requests this gateway is currently holding for the target.
	Pending       int64 `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetDemand) Reset() {
	*x = TargetDemand{}
	mi := &file_demand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetDemand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetDemand) ProtoMessage() {}

func (x *TargetDemand) ProtoReflect() protoreflect.Message {
	mi := &file_demand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetDemand.ProtoReflect.Descriptor instead.
func (*TargetDemand) Descriptor() ([]byte, []int) {
	return file_demand_proto_rawDescGZIP(), []int{1}
}

func (x *TargetDemand) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TargetDemand) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TargetDemand) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

// ReportSummary is returned once the stream closes. It exists so a gateway can
// tell an orderly shutdown from a connection that was cut.
type ReportSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of snapshots accepted on the stream.
	Snapshots     int64 `protobuf:"varint,1,opt,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSummary) Reset() {
	*x = ReportSummary{}
	mi := &file_demand_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSummary) ProtoMessage() {}

func (x *ReportSummary) ProtoReflect() protoreflect.Message {
	mi := &file_demand_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSummary.ProtoReflect.Descriptor instead.
func (*ReportSummary) Descriptor() ([]byte, []int) {
	return file_demand_proto_rawDescGZIP(), []int{2}
}

func (x *ReportSummary) GetSnapshots() int64 {
	if x != nil {
		return x.Snapshots
	}
	return 0
}

var File_demand_proto protoreflect.FileDescriptor

const file_demand_proto_rawDesc = "" +
	"\n" +
	"\fdemand.proto\x12\x19dubbo.activation.v1alpha1\"o\n" +
	"\x0eDemandSnapshot\x12\x1a\n" +
	"\breporter\x18\x01 \x01(\tR\breporter\x12A\n" +
	"\atargets\x18\x02 \x03(\v2'.dubbo.activation.v1alpha1.TargetDemandR\atargets\"`\n" +
	"\fTargetDemand\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\apending\x18\x03 \x01(\x03R\apending\"-\n" +
	"\rReportSummary\x12\x1c\n" +
	"\tsnapshots\x18\x01 \x01(\x03R\tsnapshots2u\n" +
	"\x10ActivationDemand\x12a\n" +
	"\x06Report\x12).dubbo.activation.v1alpha1.DemandSnapshot\x1a(.dubbo.activation.v1alpha1.ReportSummary\"\x00(\x01BMZKgithub.com/apache/dubbo-kubernetes/dubbod/discovery/pkg/activation/demandpbb\x06proto3"

var (
	file_demand_proto_rawDescOnce sync.Once
	file_demand_proto_rawDescData []byte
)

func file_demand_proto_rawDescGZIP() []byte {
	file_demand_proto_rawDescOnce.Do(func() {
		file_demand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demand_proto_rawDesc), len(file_demand_proto_rawDesc)))
	})
	return file_demand_proto_rawDescData
}

var file_demand_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_demand_proto_goTypes = []any{
	(*DemandSnapshot)(nil), // 0: dubbo.activation.v1alpha1.DemandSnapshot
	(*TargetDemand)(nil),   // 1: dubbo.activation.v1alpha1.TargetDemand
	(*ReportSummary)(nil),  // 2: dubbo.activation.v1alpha1.ReportSummary
}
var file_demand_proto_depIdxs = []int32{
	1, // 0: dubbo.activation.v1alpha1.DemandSnapshot.targets:type_name -> dubbo.activation.v1alpha1.TargetDemand
	0, // 1: dubbo.activation.v1alpha1.ActivationDemand.Report:input_type -> dubbo.activation.v1alpha1.DemandSnapshot
	2, // 2: dubbo.activation.v1alpha1.ActivationDemand.Report:output_type -> dubbo.activation.v1alpha1.ReportSummary
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_demand_proto_init() }
func file_demand_proto_init() {
	if File_demand_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demand_proto_rawDesc), len(file_demand_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demand_proto_goTypes,
		DependencyIndexes: file_demand_proto_depIdxs,
		MessageInfos:      file_demand_proto_msgTypes,
	}.Build()
	File_demand_proto = out.File
	file_demand_proto_goTypes = nil
	file_demand_proto_depIdxs = nil
}
