{{- $nacos := .Values -}}
{{- if eq $nacos.storage.type "mysql" }}
apiVersion: v1
kind: Service
metadata:
  name: nacos-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: nacos-mysql
    dubbo.io/rev: {{ default "default" | quote }}
    install.operator.dubbo.io/owning-resource: {{ default "unknown" }}
    operator.dubbo.io/component: "Nacos"
    dubbo: nacos
    release: {{ .Release.Name }}
    app.kubernetes.io/name: "register"
spec:
  ports:
    - name: http
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: nacos-mysql
{{- end -}}
---
{{- $nacos := .Values -}}
{{- if eq $nacos.storage.type "mysql" }}
apiVersion: v1
kind: Service
metadata:
  name: nacos-mysql-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: nacos-mysql
    dubbo.io/rev: {{ default "default" | quote }}
    install.operator.dubbo.io/owning-resource: {{ default "unknown" }}
    operator.dubbo.io/component: "Nacos"
    dubbo: nacos
    release: {{ .Release.Name }}
    app.kubernetes.io/name: "register"
spec:
  clusterIP: None
  ports:
    - name: http
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: nacos-mysql
{{- end -}}
