// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: dubbod/discovery/cmd/app/testproto/xds_test.proto

package testproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardHTTPRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Path            string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Count           int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Headers         []string               `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	RequestInterval string                 `protobuf:"bytes,5,opt,name=request_interval,json=requestInterval,proto3" json:"request_interval,omitempty"`
	Expect          string                 `protobuf:"bytes,6,opt,name=expect,proto3" json:"expect,omitempty"`
	RequestTimeout  string                 `protobuf:"bytes,7,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	WaitTimeout     string                 `protobuf:"bytes,8,opt,name=wait_timeout,json=waitTimeout,proto3" json:"wait_timeout,omitempty"`
	Namespace       string                 `protobuf:"bytes,9,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceAccount  string                 `protobuf:"bytes,10,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ForwardHTTPRequest) Reset() {
	*x = ForwardHTTPRequest{}
	mi := &file_dubbod_discovery_cmd_app_testproto_xds_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardHTTPRequest) ProtoMessage() {}

func (x *ForwardHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dubbod_discovery_cmd_app_testproto_xds_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardHTTPRequest.ProtoReflect.Descriptor instead.
func (*ForwardHTTPRequest) Descriptor() ([]byte, []int) {
	return file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardHTTPRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ForwardHTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ForwardHTTPRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ForwardHTTPRequest) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ForwardHTTPRequest) GetRequestInterval() string {
	if x != nil {
		return x.RequestInterval
	}
	return ""
}

func (x *ForwardHTTPRequest) GetExpect() string {
	if x != nil {
		return x.Expect
	}
	return ""
}

func (x *ForwardHTTPRequest) GetRequestTimeout() string {
	if x != nil {
		return x.RequestTimeout
	}
	return ""
}

func (x *ForwardHTTPRequest) GetWaitTimeout() string {
	if x != nil {
		return x.WaitTimeout
	}
	return ""
}

func (x *ForwardHTTPRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ForwardHTTPRequest) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

type ForwardHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []string               `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardHTTPResponse) Reset() {
	*x = ForwardHTTPResponse{}
	mi := &file_dubbod_discovery_cmd_app_testproto_xds_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardHTTPResponse) ProtoMessage() {}

func (x *ForwardHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dubbod_discovery_cmd_app_testproto_xds_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardHTTPResponse.ProtoReflect.Descriptor instead.
func (*ForwardHTTPResponse) Descriptor() ([]byte, []int) {
	return file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardHTTPResponse) GetOutput() []string {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_dubbod_discovery_cmd_app_testproto_xds_test_proto protoreflect.FileDescriptor

const file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDesc = "" +
	"\n" +
	"1dubbod/discovery/cmd/app/testproto/xds_test.proto\x12\x05proto\"\xc0\x02\n" +
	"\x12ForwardHTTPRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x18\n" +
	"\aheaders\x18\x04 \x03(\tR\aheaders\x12)\n" +
	"\x10request_interval\x18\x05 \x01(\tR\x0frequestInterval\x12\x16\n" +
	"\x06expect\x18\x06 \x01(\tR\x06expect\x12'\n" +
	"\x0frequest_timeout\x18\a \x01(\tR\x0erequestTimeout\x12!\n" +
	"\fwait_timeout\x18\b \x01(\tR\vwaitTimeout\x12\x1c\n" +
	"\tnamespace\x18\t \x01(\tR\tnamespace\x12'\n" +
	"\x0fservice_account\x18\n" +
	" \x01(\tR\x0eserviceAccount\"-\n" +
	"\x13ForwardHTTPResponse\x12\x16\n" +
	"\x06output\x18\x01 \x03(\tR\x06output2V\n" +
	"\x0eXDSTestService\x12D\n" +
	"\vForwardHTTP\x12\x19.proto.ForwardHTTPRequest\x1a\x1a.proto.ForwardHTTPResponseBQZOgithub.com/apache/dubbo-kubernetes/dubbod/discovery/cmd/app/testproto;testprotob\x06proto3"

var (
	file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDescOnce sync.Once
	file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDescData []byte
)

func file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDescGZIP() []byte {
	file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDescOnce.Do(func() {
		file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDesc), len(file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDesc)))
	})
	return file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDescData
}

var file_dubbod_discovery_cmd_app_testproto_xds_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dubbod_discovery_cmd_app_testproto_xds_test_proto_goTypes = []any{
	(*ForwardHTTPRequest)(nil),  // 0: proto.ForwardHTTPRequest
	(*ForwardHTTPResponse)(nil), // 1: proto.ForwardHTTPResponse
}
var file_dubbod_discovery_cmd_app_testproto_xds_test_proto_depIdxs = []int32{
	0, // 0: proto.XDSTestService.ForwardHTTP:input_type -> proto.ForwardHTTPRequest
	1, // 1: proto.XDSTestService.ForwardHTTP:output_type -> proto.ForwardHTTPResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dubbod_discovery_cmd_app_testproto_xds_test_proto_init() }
func file_dubbod_discovery_cmd_app_testproto_xds_test_proto_init() {
	if File_dubbod_discovery_cmd_app_testproto_xds_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDesc), len(file_dubbod_discovery_cmd_app_testproto_xds_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dubbod_discovery_cmd_app_testproto_xds_test_proto_goTypes,
		DependencyIndexes: file_dubbod_discovery_cmd_app_testproto_xds_test_proto_depIdxs,
		MessageInfos:      file_dubbod_discovery_cmd_app_testproto_xds_test_proto_msgTypes,
	}.Build()
	File_dubbod_discovery_cmd_app_testproto_xds_test_proto = out.File
	file_dubbod_discovery_cmd_app_testproto_xds_test_proto_goTypes = nil
	file_dubbod_discovery_cmd_app_testproto_xds_test_proto_depIdxs = nil
}
