// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for MeshGlobalConfig
func (this *MeshGlobalConfig) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MeshGlobalConfig
func (this *MeshGlobalConfig) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for MeshGlobalConfig_CertificateData
func (this *MeshGlobalConfig_CertificateData) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for MeshGlobalConfig_CertificateData
func (this *MeshGlobalConfig_CertificateData) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LabelSelector
func (this *LabelSelector) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LabelSelector
func (this *LabelSelector) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LabelSelectorRequirement
func (this *LabelSelectorRequirement) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LabelSelectorRequirement
func (this *LabelSelectorRequirement) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ConfigSource
func (this *ConfigSource) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ConfigSource
func (this *ConfigSource) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Certificate
func (this *Certificate) MarshalJSON() ([]byte, error) {
	str, err := ConfigMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Certificate
func (this *Certificate) UnmarshalJSON(b []byte) error {
	return ConfigUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ConfigMarshaler   = &jsonpb.Marshaler{}
	ConfigUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
