//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proxy.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationPolicy int32

const (
	AuthenticationPolicy_NONE       AuthenticationPolicy = 0
	AuthenticationPolicy_MUTUAL_TLS AuthenticationPolicy = 1
	AuthenticationPolicy_INHERIT    AuthenticationPolicy = 1000
)

// Enum value maps for AuthenticationPolicy.
var (
	AuthenticationPolicy_name = map[int32]string{
		0:    "NONE",
		1:    "MUTUAL_TLS",
		1000: "INHERIT",
	}
	AuthenticationPolicy_value = map[string]int32{
		"NONE":       0,
		"MUTUAL_TLS": 1,
		"INHERIT":    1000,
	}
)

func (x AuthenticationPolicy) Enum() *AuthenticationPolicy {
	p := new(AuthenticationPolicy)
	*p = x
	return p
}

func (x AuthenticationPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[0].Descriptor()
}

func (AuthenticationPolicy) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[0]
}

func (x AuthenticationPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticationPolicy.Descriptor instead.
func (AuthenticationPolicy) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

type ProxyConfig struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath                 string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	BinaryPath                 string                 `protobuf:"bytes,2,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
	DrainDuration              *durationpb.Duration   `protobuf:"bytes,4,opt,name=drain_duration,json=drainDuration,proto3" json:"drain_duration,omitempty"`
	DiscoveryAddress           string                 `protobuf:"bytes,6,opt,name=discovery_address,json=discoveryAddress,proto3" json:"discovery_address,omitempty"`
	ControlPlaneAuthPolicy     AuthenticationPolicy   `protobuf:"varint,13,opt,name=control_plane_auth_policy,json=controlPlaneAuthPolicy,proto3,enum=dubbo.mesh.v1alpha1.AuthenticationPolicy" json:"control_plane_auth_policy,omitempty"`
	CustomConfigFile           string                 `protobuf:"bytes,14,opt,name=custom_config_file,json=customConfigFile,proto3" json:"custom_config_file,omitempty"`
	ProxyBootstrapTemplatePath string                 `protobuf:"bytes,17,opt,name=proxy_bootstrap_template_path,json=proxyBootstrapTemplatePath,proto3" json:"proxy_bootstrap_template_path,omitempty"`
	ProxyMetadata              map[string]string      `protobuf:"bytes,24,rep,name=proxy_metadata,json=proxyMetadata,proto3" json:"proxy_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StatusPort                 int32                  `protobuf:"varint,26,opt,name=status_port,json=statusPort,proto3" json:"status_port,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ProxyConfig) Reset() {
	*x = ProxyConfig{}
	mi := &file_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConfig) ProtoMessage() {}

func (x *ProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConfig.ProtoReflect.Descriptor instead.
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyConfig) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *ProxyConfig) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *ProxyConfig) GetDrainDuration() *durationpb.Duration {
	if x != nil {
		return x.DrainDuration
	}
	return nil
}

func (x *ProxyConfig) GetDiscoveryAddress() string {
	if x != nil {
		return x.DiscoveryAddress
	}
	return ""
}

func (x *ProxyConfig) GetControlPlaneAuthPolicy() AuthenticationPolicy {
	if x != nil {
		return x.ControlPlaneAuthPolicy
	}
	return AuthenticationPolicy_NONE
}

func (x *ProxyConfig) GetCustomConfigFile() string {
	if x != nil {
		return x.CustomConfigFile
	}
	return ""
}

func (x *ProxyConfig) GetProxyBootstrapTemplatePath() string {
	if x != nil {
		return x.ProxyBootstrapTemplatePath
	}
	return ""
}

func (x *ProxyConfig) GetProxyMetadata() map[string]string {
	if x != nil {
		return x.ProxyMetadata
	}
	return nil
}

func (x *ProxyConfig) GetStatusPort() int32 {
	if x != nil {
		return x.StatusPort
	}
	return 0
}

var File_proxy_proto protoreflect.FileDescriptor

const file_proxy_proto_rawDesc = "" +
	"\n" +
	"\vproxy.proto\x12\x13dubbo.mesh.v1alpha1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8b\x05\n" +
	"\vProxyConfig\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\x12\x1f\n" +
	"\vbinary_path\x18\x02 \x01(\tR\n" +
	"binaryPath\x12@\n" +
	"\x0edrain_duration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\rdrainDuration\x12+\n" +
	"\x11discovery_address\x18\x06 \x01(\tR\x10discoveryAddress\x12d\n" +
	"\x19control_plane_auth_policy\x18\r \x01(\x0e2).dubbo.mesh.v1alpha1.AuthenticationPolicyR\x16controlPlaneAuthPolicy\x12,\n" +
	"\x12custom_config_file\x18\x0e \x01(\tR\x10customConfigFile\x12A\n" +
	"\x1dproxy_bootstrap_template_path\x18\x11 \x01(\tR\x1aproxyBootstrapTemplatePath\x12Z\n" +
	"\x0eproxy_metadata\x18\x18 \x03(\v23.dubbo.mesh.v1alpha1.ProxyConfig.ProxyMetadataEntryR\rproxyMetadata\x12\x1f\n" +
	"\vstatus_port\x18\x1a \x01(\x05R\n" +
	"statusPort\x1a@\n" +
	"\x12ProxyMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x05\x10\x06J\x04\b\t\x10\n" +
	"R\x18parent_shutdown_durationR\x0fconnect_timeout*>\n" +
	"\x14AuthenticationPolicy\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0e\n" +
	"\n" +
	"MUTUAL_TLS\x10\x01\x12\f\n" +
	"\aINHERIT\x10\xe8\aB\x14Z\x12/api/mesh/v1alpha1b\x06proto3"

var (
	file_proxy_proto_rawDescOnce sync.Once
	file_proxy_proto_rawDescData []byte
)

func file_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)))
	})
	return file_proxy_proto_rawDescData
}

var file_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_proto_goTypes = []any{
	(AuthenticationPolicy)(0),   // 0: dubbo.mesh.v1alpha1.AuthenticationPolicy
	(*ProxyConfig)(nil),         // 1: dubbo.mesh.v1alpha1.ProxyConfig
	nil,                         // 2: dubbo.mesh.v1alpha1.ProxyConfig.ProxyMetadataEntry
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_proxy_proto_depIdxs = []int32{
	3, // 0: dubbo.mesh.v1alpha1.ProxyConfig.drain_duration:type_name -> google.protobuf.Duration
	0, // 1: dubbo.mesh.v1alpha1.ProxyConfig.control_plane_auth_policy:type_name -> dubbo.mesh.v1alpha1.AuthenticationPolicy
	2, // 2: dubbo.mesh.v1alpha1.ProxyConfig.proxy_metadata:type_name -> dubbo.mesh.v1alpha1.ProxyConfig.ProxyMetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proxy_proto_init() }
func file_proxy_proto_init() {
	if File_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proto_depIdxs,
		EnumInfos:         file_proxy_proto_enumTypes,
		MessageInfos:      file_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proto = out.File
	file_proxy_proto_goTypes = nil
	file_proxy_proto_depIdxs = nil
}
