// Code generated by pkg/config/schema/codegen/tools/collections.main.go. DO NOT EDIT.

package kubetypes

import (
	"github.com/apache/dubbo-kubernetes/pkg/config"
	"github.com/apache/dubbo-kubernetes/pkg/config/schema/gvk"
	githubcomdubmlapimeshv1alpha1 "github.com/dubml/api/mesh/v1alpha1"
	githubcomdubmlapinetworkingv1alpha3 "github.com/dubml/api/networking/v1alpha3"
	githubcomdubmlapisecurityv1alpha3 "github.com/dubml/api/security/v1alpha3"
	githubcomdubmlapitelemetryv1alpha3 "github.com/dubml/api/telemetry/v1alpha3"
	apigithubcomapachedubbokubernetesapinetworkingv1alpha3 "github.com/dubml/client-go/pkg/apis/networking/v1alpha3"
	apigithubcomapachedubbokubernetesapisecurityv1alpha3 "github.com/dubml/client-go/pkg/apis/security/v1alpha3"
	apigithubcomapachedubbokubernetesapitelemetryv1alpha3 "github.com/dubml/client-go/pkg/apis/telemetry/v1alpha3"
	k8sioapiadmissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	k8sioapiappsv1 "k8s.io/api/apps/v1"
	k8sioapicoordinationv1 "k8s.io/api/coordination/v1"
	k8sioapicorev1 "k8s.io/api/core/v1"
	k8sioapidiscoveryv1 "k8s.io/api/discovery/v1"
	k8sioapipolicyv1 "k8s.io/api/policy/v1"
	k8sioapiextensionsapiserverpkgapisapiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	sigsk8siogatewayapiapisv1 "sigs.k8s.io/gateway-api/apis/v1"
	sigsk8siogatewayapiapisv1beta1 "sigs.k8s.io/gateway-api/apis/v1beta1"
)

func getGvk(obj any) (config.GroupVersionKind, bool) {
	switch obj.(type) {
	case *githubcomdubmlapisecurityv1alpha3.AuthorizationPolicy:
		return gvk.AuthorizationPolicy, true
	case *apigithubcomapachedubbokubernetesapisecurityv1alpha3.AuthorizationPolicy:
		return gvk.AuthorizationPolicy, true
	case *sigsk8siogatewayapiapisv1.BackendTLSPolicy:
		return gvk.BackendTLSPolicy, true
	case *githubcomdubmlapinetworkingv1alpha3.CircuitBreakerPolicy:
		return gvk.CircuitBreakerPolicy, true
	case *apigithubcomapachedubbokubernetesapinetworkingv1alpha3.CircuitBreakerPolicy:
		return gvk.CircuitBreakerPolicy, true
	case *k8sioapicorev1.ConfigMap:
		return gvk.ConfigMap, true
	case *k8sioapiextensionsapiserverpkgapisapiextensionsv1.CustomResourceDefinition:
		return gvk.CustomResourceDefinition, true
	case *k8sioapiappsv1.DaemonSet:
		return gvk.DaemonSet, true
	case *k8sioapiappsv1.Deployment:
		return gvk.Deployment, true
	case *k8sioapidiscoveryv1.EndpointSlice:
		return gvk.EndpointSlice, true
	case *k8sioapicorev1.Endpoints:
		return gvk.Endpoints, true
	case *githubcomdubmlapinetworkingv1alpha3.FaultInjectionPolicy:
		return gvk.FaultInjectionPolicy, true
	case *apigithubcomapachedubbokubernetesapinetworkingv1alpha3.FaultInjectionPolicy:
		return gvk.FaultInjectionPolicy, true
	case *sigsk8siogatewayapiapisv1.GatewayClass:
		return gvk.GatewayClass, true
	case *sigsk8siogatewayapiapisv1.HTTPRoute:
		return gvk.HTTPRoute, true
	case *sigsk8siogatewayapiapisv1.Gateway:
		return gvk.KubernetesGateway, true
	case *k8sioapicoordinationv1.Lease:
		return gvk.Lease, true
	case *githubcomdubmlapimeshv1alpha1.MeshConfig:
		return gvk.MeshConfig, true
	case *k8sioapiadmissionregistrationv1.MutatingWebhookConfiguration:
		return gvk.MutatingWebhookConfiguration, true
	case *k8sioapicorev1.Namespace:
		return gvk.Namespace, true
	case *k8sioapicorev1.Node:
		return gvk.Node, true
	case *githubcomdubmlapisecurityv1alpha3.PeerAuthentication:
		return gvk.PeerAuthentication, true
	case *apigithubcomapachedubbokubernetesapisecurityv1alpha3.PeerAuthentication:
		return gvk.PeerAuthentication, true
	case *k8sioapicorev1.Pod:
		return gvk.Pod, true
	case *k8sioapipolicyv1.PodDisruptionBudget:
		return gvk.PodDisruptionBudget, true
	case *sigsk8siogatewayapiapisv1beta1.ReferenceGrant:
		return gvk.ReferenceGrant, true
	case *githubcomdubmlapisecurityv1alpha3.RequestAuthentication:
		return gvk.RequestAuthentication, true
	case *apigithubcomapachedubbokubernetesapisecurityv1alpha3.RequestAuthentication:
		return gvk.RequestAuthentication, true
	case *k8sioapicorev1.Secret:
		return gvk.Secret, true
	case *k8sioapicorev1.Service:
		return gvk.Service, true
	case *k8sioapicorev1.ServiceAccount:
		return gvk.ServiceAccount, true
	case *githubcomdubmlapinetworkingv1alpha3.ServiceEntry:
		return gvk.ServiceEntry, true
	case *apigithubcomapachedubbokubernetesapinetworkingv1alpha3.ServiceEntry:
		return gvk.ServiceEntry, true
	case *k8sioapiappsv1.StatefulSet:
		return gvk.StatefulSet, true
	case *githubcomdubmlapitelemetryv1alpha3.Telemetry:
		return gvk.Telemetry, true
	case *apigithubcomapachedubbokubernetesapitelemetryv1alpha3.Telemetry:
		return gvk.Telemetry, true
	case *githubcomdubmlapinetworkingv1alpha3.TransitService:
		return gvk.TransitService, true
	case *apigithubcomapachedubbokubernetesapinetworkingv1alpha3.TransitService:
		return gvk.TransitService, true
	case *k8sioapiadmissionregistrationv1.ValidatingWebhookConfiguration:
		return gvk.ValidatingWebhookConfiguration, true
	case *githubcomdubmlapinetworkingv1alpha3.WorkloadEntry:
		return gvk.WorkloadEntry, true
	case *apigithubcomapachedubbokubernetesapinetworkingv1alpha3.WorkloadEntry:
		return gvk.WorkloadEntry, true
	default:
		return config.GroupVersionKind{}, false
	}
}
