{{- $admin := .Values -}}
{{- $cp := .Values.cp -}}
{{- $zoo := .Values.zookeeper }}
{{- $nacos := .Values.nacos }}
{{- $prom := .Values.kubePrometheus }}
{{- if eq $admin.deployType "Deployment" }}
apiVersion: {{ template "apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "admin.name" . }}
  namespace: {{ template "admin.namespace" . }}
  labels:
  {{- include "admin.labels" . | nindent 4 }}
  {{- with $admin.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $admin.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $admin.replicas }}
  {{- if $admin.revisionHistoryLimit }}
  revisionHistoryLimit: {{ $admin.revisionHistoryLimit }}
  {{- end }}
  {{- if $admin.minReadySeconds }}
  minReadySeconds: {{ $admin.minReadySeconds }}
  {{- end }}
  strategy:
  {{- if $admin.strategy }}
  {{- toYaml $admin.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
    {{- include "admin.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "admin.labels" . | nindent 8 }}
    spec:
      {{- if $admin.imagePullSecrets }}
      imagePullSecrets: {{ toYaml $admin.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if $admin.nodeSelector }}
      nodeSelector: {{ toYaml $admin.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $admin.tolerations }}
      tolerations: {{ toYaml $admin.tolerations | nindent 8 }}
      {{- end }}
      {{- if $admin.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ $admin.terminationGracePeriodSeconds }}
      {{- end }}
      serviceAccountName: {{ template "admin.name" . }}
      containers:
      - name: admin
        image: {{ $admin.image.registry }}:{{ $admin.image.tag }}
        imagePullPolicy: {{ $admin.image.pullPolicy }}
        lifecycle:
        {{- if $admin.lifecycleHooks }}
        {{- toYaml $admin.lifecycleHooks | nindent 10 }}
        {{- end }}
        args:
        - run
        - --config-file=/etc/dubbo.io/cp-config/config.yaml
        ports:
        - name: admin-http
          containerPort: {{ template "admin.web.containerPort" . }}
        - name: admin-xds-grpc
          containerPort: {{ template "admin.xds.containerPort" . }}
        - name: admin-admission
          containerPort: {{ template "admin.admissionServer.containerPort" . }}
        env:
        {{- $zooName := include "zoo.name" . -}}
        {{- $nacosName := include "nacos.name" . -}}
        {{- $zooReplicas := int .Values.zookeeper.replicas -}}
        {{- $nacosReplicas := int $nacos.replicas -}}
        {{- $zooHeadless := printf "%s-%s" $zooName "headless" | trunc 63 -}}
        {{- $nacosHeadless := printf "%s-%s" $nacosName "headless" | trunc 63 -}}
        {{- $zooNamespace := include "admin.namespace" . -}}
        {{- $nacosNamespace := include "admin.namespace" . -}}
        {{- $clusterDomain := $admin.clusterDomain -}}
        {{- $zooPort := include "zoo.client" . -}}
        {{- $nacosPort := $nacos.serverPort -}}
        {{- $register := .Values.register }}
        {{- if (eq $register true) | default true }}
        {{- if $zoo.enabled }}
        - name: DUBBO_STORE_TRADITIONAL_REGISTRY
          value: zookeeper://{{ $zooName }}.{{ $zooNamespace }}.svc.{{ $clusterDomain }}:{{ $zooPort }}
          {{- else if $nacos.enabled }}
        - name: DUBBO_STORE_TRADITIONAL_REGISTRY
          value: nacos://{{ range $k, $v := until $nacosReplicas }}{{ $nacosName }}-{{ $v }}.{{ $nacosName }}.{{ $nacosNamespace }}.svc.{{ $clusterDomain }}:{{ $nacosPort }}{{ if ne (add $k 1) $nacosReplicas }},{{ end }}{{ end }}
          {{- else }}
        - name: DUBBO_STORE_TRADITIONAL_REGISTRY
          value: zookeeper://{{ range $k, $v := until $zooReplicas }}{{ $zooName }}-{{ $v }}.{{ $zooName }}.{{ $zooNamespace }}.svc.{{ $clusterDomain }}:{{ $zooPort }}{{ if ne (add $k 1) $zooReplicas }},{{ end }}{{ end }}
        {{- end }}
        {{- end }}
        - name: DUBBO_RUNTIME_KUBERNETES_ADMISSION_SERVER_CERT_DIR
          value: /var/run/secrets/dubbo.io/tls-cert
        {{- $promName := include "prom.name" . }}
        {{- $promPort := include "prom.port" . }}
        {{- $promStationaryName := printf "kube-prome-prometheus" }}
        {{- $promFullName := printf "%s-%s" $promName $promStationaryName }}
        {{- if $prom.enabled }}
        - name: ADMIN_PROMETHEUS_ADDRESS
          value: {{ $promFullName }}:{{ $promPort }}
        {{- $grafanaName := include "grafana.name" . }}
        {{- $grafanaPort := include "grafana.port" . }}
        {{- $grafanaFullName := printf "%s-%s" $promName $grafanaName }}
        - name: ADMIN_GRAFANA_ADDRESS
          value: {{ $grafanaFullName }}:{{ $grafanaPort }}
        {{- end }}
        volumeMounts:
        {{- if $admin.volumeMounts }}
        {{- toYaml $admin.volumeMounts | nindent 8 }}
        {{- end }}
        - name: general-tls-cert
          mountPath: /var/run/secrets/dubbo.io/tls-cert/tls.crt
          subPath: tls.crt
          readOnly: true
        - name: general-tls-cert
          mountPath: /var/run/secrets/dubbo.io/tls-cert/tls.key
          subPath: tls.key
          readOnly: true
        - name: general-tls-cert{{- if $cp.tls.caSecretName }}-ca{{- end }}
          mountPath: /var/run/secrets/dubbo.io/tls-cert/ca.crt
          subPath: ca.crt
          readOnly: true
        - name: cp-config
          mountPath: /etc/dubbo.io/cp-config/config.yaml
          subPath: config.yaml
          readOnly: true
        securityContext:
        {{- if $admin.securityContext }}
        {{- toYaml $admin.securityContext | nindent 10 }}
        {{- end }}
        startupProbe:
        {{- if $admin.startupProbe }}
        {{- toYaml $admin.startupProbe | nindent 10 }}
        {{- end }}
        livenessProbe:
        {{- if $admin.livenessProbe }}
        {{- toYaml $admin.livenessProbe | nindent 10 }}
        {{- end }}
        readinessProbe:
        {{- if $admin.readinessProbe }}
        {{- toYaml $admin.readinessProbe | nindent 10 }}
        {{- end }}
        resources:
        {{- if $admin.resources }}
        {{- toYaml $admin.resources | nindent 10 }}
        {{- end }}
      volumes:
      {{- if $admin.volumes }}
      {{- toYaml $admin.volumes | nindent 6 }}
      {{- end }}
      - name: cp-config
        configMap:
          name: {{ include "admin.name" . }}-control-plane-config
      {{- if $cp.tls.secretName }}
      - name: general-tls-cert
        secret:
          secretName: {{ $cp.tls.secretName }}
      {{- else }}
      - name: general-tls-cert
        secret:
          secretName: {{ include "admin.name" . }}-tls-cert
      {{- end }}
      {{- if $cp.tls.caSecretName }}
      - name: general-tls-cert-ca
        secret:
          secretName: {{ $cp.tls.caSecretName }}
      {{- end }}
      - name: storage
        {{- if $admin.persistence.enabled }}
        persistentVolumeClaim:
        {{- with $admin.persistence }}
        {{- if .claimName }}
          claimName: {{ .claimName }}
        {{- else }}
        emptyDir: {}
        {{- end -}}
        {{- end -}}
        {{- end -}}
{{- end -}}
