{{ $adminCpLabels := include "admin.labels" . }}
{{- $admin := .Values -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin.name" . }}-control-plane-config
  namespace: {{ template "admin.namespace" . }}
  labels:
  {{- include "admin.labels" . | nindent 4 }}
  {{- with $admin.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{/* TODO */}}
  dubbo-cp.yaml: |-
    {{- if $admin.cp }}
    {{ toYaml $admin.cp | nindent 4 | trim }}
    {{ end }}
