{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled }}
apiVersion: {{ template "network.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "admin.name" . }}-ingress
  namespace: {{ template "system.namespaces" . }}
spec:
  ingressClassName: {{ template "traefik.name" . }}
  rules:
  - host: {{ $ingress.hosts.admin }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "admin.name" . }}
            port:
              number: {{ template "admin.port" . }}
---
apiVersion: {{ template "network.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "prom.name" . }}-ingress
  namespace: {{ template "system.namespaces" . }}
spec:
  ingressClassName: {{ template "traefik.name" . }}
  rules:
  - host: {{ $ingress.hosts.prometheus }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "prom.name" . }}
            port:
              number: {{ template "prom.port" . }}
---
apiVersion: {{ template "network.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "grafana.name" . }}-ingress
  namespace: {{ template "system.namespaces" . }}
spec:
  ingressClassName: {{ template "traefik.name" . }}
  rules:
  - host: {{ $ingress.hosts.grafana }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "grafana.name" . }}
            port:
              number: {{ template "grafana.port" . }}
  {{- end -}}