annotations:
  licenses: Apache-2.0

name: register-discovery
home: https://github.com/apache/dubbo-kubernetes
description: ""
apiVersion: v2
appVersion: 0.1.0
kubeVersion: '>=1.28.0-0'

maintainers:
  - name: mfordjody
    email: zhongxjian@apache.org

sources:
  - https://github.com/apache/dubbo-kubernetes
  - https://dubbo.apache.org
version: 3.3.0
