{{- $zookeeper := .Values -}}
{{- $zoo := .Values.zookeeper }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: {{ .Release.Namespace }}
  labels:
    app: zookeeper
    dubbo.io/rev: {{ default "default" | quote }}
    install.operator.dubbo.io/owning-resource: {{ default "unknown" }}
    operator.dubbo.io/component: "Zookeeper"
    dubbo: zookeeper
    release: {{ .Release.Name }}
    app.kubernetes.io/name: "register"
spec:
  selector:
    matchLabels:
      app: zookeeper
      dubbo.io/rev: {{ default "default" | quote }}
      dubbo: zookeeper
  replicas: {{ $zookeeper.replicas }}
  serviceName: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        dubbo.io/rev: {{ default "default" | quote }}
        install.operator.dubbo.io/owning-resource: {{ default "unknown" }}
        operator.dubbo.io/component: "Zookeeper"
        dubbo: zookeeper
        release: {{ .Release.Name }}
        app.kubernetes.io/name: "register"
    spec:
      containers:
      - name: zookeeper
        image: {{ $zookeeper.image }}:{{ $zookeeper.tag }}
        imagePullPolicy: {{ $zookeeper.imagePullPolicy }}
        resources:
{{ toYaml $zookeeper.resources | trim | indent 10 }}
        ports:
        - name: client
          containerPort: 2181
        - name: follower
          containerPort: 2888
        - name: election
          containerPort: 3888
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper
      volumes:
      - name: scripts
        configMap:
          name: zookeeper-scripts
          defaultMode: 0755
      - name: data
        hostPath:
          path: /var/lib/zookeeper