{{- $zookeeper := .Values -}}
{{- $zoo := .Values.zookeeper }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: {{ .Release.Namespace }}
  labels:
    app: zookeeper
    dubbo.io/rev: {{ default "default" | quote }}
    install.operator.dubbo.io/owning-resource: {{ default "unknown" }}
    operator.dubbo.io/component: "Zookeeper"
    dubbo: zookeeper
    release: {{ .Release.Name }}
    app.kubernetes.io/name: "register"
spec:
  selector:
    matchLabels:
      app: zookeeper
      dubbo.io/rev: {{ default "default" | quote }}
      dubbo: zookeeper
  replicas: {{ $zookeeper.replicas }}
  serviceName: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        dubbo.io/rev: {{ default "default" | quote }}
        install.operator.dubbo.io/owning-resource: {{ default "unknown" }}
        operator.dubbo.io/component: "Zookeeper"
        dubbo: zookeeper
        release: {{ .Release.Name }}
        app.kubernetes.io/name: "register"
    spec:
      containers:
      - name: zookeeper
        image: zookeeper
        imagePullPolicy: {{ $zookeeper.imagePullPolicy }}
        env:
        - name: DATA_LOG_DIR
          value: ''
        - name: TICK_TIME
          value: "2000"
        - name: INIT_LIMIT
          value: "10"
        - name: SYNC_LIMIT
          value: "5"
        - name: PORT_NUMBER
          value: "2181"
        - name: PRE_ALLOC_SIZE
          value: "65536"
        - name: SNAPCOUNT
          value: "100000"
        - name: MAX_CLIENT_CNXNS
          value: "60"
        - name: 4LW_COMMANDS_WHITELIST
          value: "srvr, mntr, ruok"
        - name: LISTEN_ALLIPS_ENABLED
          value: "no"
        - name: AUTOPURGE_INTERVAL
          value: "1"
        - name: AUTOPURGE_RETAIN_COUNT
          value: "10"
        - name: MAX_SESSION_TIMEOUT
          value: "40000"
        - name: ENABLE_AUTH
          value: "no"
        - name: ENABLE_QUORUM_AUTH
          value: "no"
        - name: HEAP_SIZE
          value: "1024"
        - name: LOG_LEVEL
          value: "ERROR"
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ADMIN_SERVER_PORT_NUMBER
          value: "8080"
        - name: SERVERS
          value: "zookeeper-0.zookeeper-headless:2888:3888::1"
        resources:
{{ toYaml $zookeeper.resources | trim | indent 10 }}
        ports:
        - name: client
          containerPort: 2181
        - name: follower
          containerPort: 2888
        - name: election
          containerPort: 3888
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper
      volumes:
      - name: scripts
        configMap:
          name: zookeeper-scripts
          defaultMode: 0755
      - name: data
        emptyDir: {}
{{/*  volumeClaimTemplates:*/}}
{{/*  - metadata:*/}}
{{/*      name: data*/}}
{{/*    spec:*/}}
{{/*      accessModes:*/}}
{{/*        - ReadWriteOnce*/}}
{{/*      resources:*/}}
{{/*        requests:*/}}
{{/*          storage: 5Gi*/}}
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: PersistentVolumeClaim*/}}
{{/*metadata:*/}}
{{/*  name: zookeeper-pvc*/}}
{{/*spec:*/}}
{{/*  storageClassName: rook-ceph-block*/}}
{{/*  accessModes:*/}}
{{/*    - ReadWriteOnce*/}}
{{/*  resources:*/}}
{{/*    requests:*/}}
{{/*      storage: 20Gi*/}}