{{- $zookeeper := .Values -}}
{{- $zoo := .Values.zookeeper }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: {{ .Release.Namespace }}
  labels:
    app: zookeeper
    dubbo.io/rev: {{ default "default" | quote }}
    install.operator.dubbo.io/owning-resource: {{ default "unknown" }}
    operator.dubbo.io/component: "Zookeeper"
    dubbo: zookeeper
    release: {{ .Release.Name }}
    app.kubernetes.io/name: "register"
spec:
  selector:
    matchLabels:
      app: zookeeper
      dubbo.io/rev: {{ default "default" | quote }}
      dubbo: zookeeper
  replicas: {{ $zookeeper.replicas }}
  serviceName: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        dubbo.io/rev: {{ default "default" | quote }}
        install.operator.dubbo.io/owning-resource: {{ default "unknown" }}
        operator.dubbo.io/component: "Zookeeper"
        dubbo: zookeeper
        release: {{ .Release.Name }}
        app.kubernetes.io/name: "register"
    spec:
      containers:
      - name: zookeeper
        image: zookeeper
        imagePullPolicy: {{ $zookeeper.imagePullPolicy }}
        env:
        # The number of milliseconds of each tick
        - name: TICK_TIME
          value: "2000"
        # The number of ticks that the initial
        # synchronization phase can take
        - name: INIT_LIMIT
          value: "10"
        # The number of ticks that can pass between
        # sending a request and getting an acknowledgement
        - name: SYNC_LIMIT
          value: "5"
        # the directory where the snapshot is stored.
        # do not use /tmp for storage, /tmp here is just
        # example sakes.
        - name: DATA_LOG_DIR
          value: ''
        # the port at which the clients will connect
        - name: PORT_NUMBER
          value: "2181"
        resources:
{{ toYaml $zookeeper.resources | trim | indent 10 }}
        ports:
        - name: client
          containerPort: 2181
        - name: follower
          containerPort: 2888
        - name: election
          containerPort: 3888
        volumeMounts:
        - name: data
          mountPath: /var/lib/zookeeper
      volumes:
      - name: scripts
        configMap:
          name: zookeeper-scripts
          defaultMode: 0755
      - name: data
        emptyDir: {}
{{/*  volumeClaimTemplates:*/}}
{{/*  - metadata:*/}}
{{/*      name: data*/}}
{{/*    spec:*/}}
{{/*      accessModes:*/}}
{{/*        - ReadWriteOnce*/}}
{{/*      resources:*/}}
{{/*        requests:*/}}
{{/*          storage: 5Gi*/}}
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: PersistentVolumeClaim*/}}
{{/*metadata:*/}}
{{/*  name: zookeeper-pvc*/}}
{{/*spec:*/}}
{{/*  storageClassName: rook-ceph-block*/}}
{{/*  accessModes:*/}}
{{/*    - ReadWriteOnce*/}}
{{/*  resources:*/}}
{{/*    requests:*/}}
{{/*      storage: 20Gi*/}}