{{- $zookeeper := .Values -}}
{{- $zoo := .Values.zookeeper }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "zoo.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "zoo.labels" . | nindent 4 }}
  {{- with $zookeeper.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with $zookeeper.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $zookeeper.replicas }}
  selector:
    matchLabels:
    {{- include "zoo.matchLabels" . | nindent 6 }}
  serviceName: {{ template "zoo.name" . }}
  template:
    metadata:
      labels:
      {{- include "zoo.labels" . | nindent 8 }}
    spec:
      securityContext:
      {{- if $zookeeper.securityContext.enabled }}
      {{- omit $zookeeper.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: zookeeper
        image: {{ $zookeeper.image.registry }}:{{ $zookeeper.image.tag }}
        imagePullPolicy: {{ $zookeeper.image.pullPolicy }}
        securityContext:
        {{- if $zookeeper.containerSecurityContext.enabled }}
        {{- omit $zookeeper.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        command:
        - /scripts/setup.sh
        resources:
        {{- if $zookeeper.resources }}
        {{- toYaml $zookeeper.resources | nindent 10 }}
        {{- end }}
        env:
        - name: BITNAMI_DEBUG
          value: {{ ternary "true" "false" (or $zookeeper.image.debug) | quote }}
        - name: ZOO_DATA_LOG_DIR
          value: {{ $zookeeper.dataLogDir | default $zoo.dataLogDir | quote }}
        - name: ZOO_PORT_NUMBER
          value: {{ 2181 | quote }}
        - name: ZOO_TICK_TIME
          value: {{ $zookeeper.tickTime | quote }}
        - name: ZOO_INIT_LIMIT
          value: {{ $zookeeper.initLimit | default $zoo.initLimit | quote }}
        - name: ZOO_SYNC_LIMIT
          value: {{ $zookeeper.syncLimit | quote }}
        - name: ZOO_PRE_ALLOC_SIZE
          value: {{ $zookeeper.preAllocSize | quote }}
        - name: ZOO_SNAPCOUNT
          value: {{ $zookeeper.snapCount | quote }}
        - name: ZOO_MAX_CLIENT_CNXNS
          value: {{ $zookeeper.maxClientCnxns | quote }}
        - name: ZOO_4LW_COMMANDS_WHITELIST
          value: {{ $zookeeper.fourlwCommandsWhitelist | quote }}
        - name: ZOO_LISTEN_ALLIPS_ENABLED
          value: {{ ternary "yes" "no" $zookeeper.listenOnAllIPs | quote }}
        - name: ZOO_AUTOPURGE_INTERVAL
          value: {{ $zookeeper.autopurge.purgeInterval | quote }}
        - name: ZOO_AUTOPURGE_RETAIN_COUNT
          value: {{ $zookeeper.autopurge.snapRetainCount | quote }}
        - name: ZOO_MAX_SESSION_TIMEOUT
          value: {{ $zookeeper.maxSessionTimeout | quote }}
        {{- $zooName := include "zoo.name" . }}
        {{- $zooReplicas := int $zookeeper.replicas  }}
        {{- $zooHeadless := printf "%s-%s" $zooName "headless" | trunc 63 }}
        {{- $zooNamespace := .Release.Namespace }}
        {{- $zooDomain := $zookeeper.clusterDomain }}
        - name: ZOO_SERVERS
          value: {{ range $k, $v := until $zooReplicas }}{{ $zooName }}-{{ $v }}.{{ $zooName }}.{{ $zooNamespace }}.svc.{{ $zooDomain }}:2888:3888::{{ add $v 1 }} {{ end }}
        - name: ZOO_ENABLE_AUTH
          value: {{ ternary "no" "yes" $zookeeper.auth.client.enabled | quote }}
        - name: ALLOW_ANONYMOUS_LOGIN
          value: {{ ternary "no" "yes" $zookeeper.auth.client.enabled | quote }}
        {{- if $zookeeper.auth.client.enabled }}
        - name: ZOO_CLIENT_USER
          value: {{ $zookeeper.auth.client.clientUser | quote }}
        - name: ZOO_CLIENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "zoo.client.secretName" . }}
              key: client-password
        - name: ZOO_SERVER_USERS
          value: {{ $zookeeper.auth.client.serverUsers | quote }}
        - name: ZOO_SERVER_PASSWORDS
          valueFrom:
            secretKeyRef:
              name: {{ include "zoo.client.secretName" . }}
              key: server-password
        {{- end }}
        - name: ZOO_ENABLE_QUORUM_AUTH
          value: {{ ternary "yes" "no" $zookeeper.auth.quorum.enabled | quote }}
        {{- if $zookeeper.auth.quorum.enabled }}
        - name: ZOO_QUORUM_LEARNER_USER
          value: {{ $zookeeper.auth.quorum.learnerUser | quote }}
        - name: ZOO_QUORUM_LEARNER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "zoo.quorum.secretName" . }}
              key: quorum-learner-password
        - name: ZOO_QUORUM_SERVER_USERS
          value: {{ $zookeeper.auth.quorum.serverUsers | quote }}
        - name: ZOO_QUORUM_SERVER_PASSWORDS
          valueFrom:
            secretKeyRef:
              name: {{ include "zoo.quorum.secretName" . }}
              key: quorum-server-password
        {{- end }}
        - name: ZOO_HEAP_SIZE
          value: {{ $zookeeper.heapSize | quote }}
        - name: ZOO_LOG_LEVEL
          value: {{ $zookeeper.logLevel | quote }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        ports:
        - name: client
          containerPort: {{ template "zoo.client" . }}
        - name: follower
          containerPort: {{ template "zoo.follower" . }}
        - name: election
          containerPort: {{ template "zoo.election" . }}
        startupProbe:
        {{- if $zookeeper.startupProbe }}
        {{- toYaml $zookeeper.startupProbe | nindent 10 }}
        {{- end }}
        readinessProbe:
        {{- if $zookeeper.readinessProbe }}
        {{- toYaml $zookeeper.readinessProbe | nindent 10 }}
        {{- end }}
        livenessProbe:
        {{- if $zookeeper.livenessProbe }}
        {{- toYaml $zookeeper.livenessProbe | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: scripts
          mountPath: /scripts/setup.sh
          subPath: setup.sh
        - name: data
          mountPath: /bitnami/zookeeper
      volumes:
      - name: scripts
        configMap:
          name: {{ template "zoo.name" . }}-scripts
          defaultMode: 0755
      - name: data
        emptyDir: {}