meshConfig:
  trustDomainAliases:
    - old.cluster.local
  minimumTlsVersion: TLSV1_3
  extensionProviders:
    - name: opa
      envoyExtAuthzHttp:
        service: opa.security.svc.cluster.local
        port: 9191
        pathPrefix: /check
        includeRequestHeadersInCheck:
          - authorization
          - x-jwt-sub
        headersToUpstreamOnAllow:
          - x-authz-user
        headersToDownstreamOnDeny:
          - x-authz-reason
        timeout: 2s
        failOpen: false

