# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  labels:
    app: provider
  name: provider
  namespace: grpc-app
spec:
  selector:
    app: provider
  type: ClusterIP
  ports:
    - name: grpc
      port: 7070
      targetPort: 17070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-v1
  namespace: grpc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
      version: v1
  template:
    metadata:
      annotations:
        proxyless.dubbo.apache.org/inject: "true"
        inject.dubbo.apache.org/templates: grpc-agent
      labels:
        app: provider
        version: v1
    spec:
      containers:
        - name: app
          image: mfordjody/grpc-provider:dev-debug
          imagePullPolicy: Always
          ports:
            - containerPort: 17070
              protocol: TCP
              name: grpc
          env:
            - name: GRPC_XDS_EXPERIMENTAL_SECURITY_SUPPORT
              value: "true"
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SERVICE_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
            - name: SERVICE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_PORT
              value: "17070"
          volumeMounts:
            - mountPath: /var/lib/dubbo/data
              name: dubbo-data
          readinessProbe:
            tcpSocket:
              port: 17070
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 17070
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: dubbo-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-v2
  namespace: grpc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
      version: v2
  template:
    metadata:
      annotations:
        proxyless.dubbo.apache.org/inject: "true"
        inject.dubbo.apache.org/templates: grpc-agent
      labels:
        app: provider
        version: v2
    spec:
      containers:
        - name: app
          image: mfordjody/grpc-provider:dev-debug
          imagePullPolicy: Always
          ports:
            - containerPort: 17070
              protocol: TCP
              name: grpc
          env:
            - name: GRPC_XDS_EXPERIMENTAL_SECURITY_SUPPORT
              value: "true"
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: SERVICE_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
            - name: SERVICE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_PORT
              value: "17070"
          volumeMounts:
            - mountPath: /var/lib/dubbo/data
              name: dubbo-data
          readinessProbe:
            tcpSocket:
              port: 17070
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 17070
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: dubbo-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: grpc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      annotations:
        proxyless.dubbo.apache.org/inject: "true"
        inject.dubbo.apache.org/templates: grpc-agent
      labels:
        app: consumer
    spec:
      containers:
        - name: app
          # Replace with your own image containing the consumer binary
          image: mfordjody/grpc-consumer:dev-debug
          imagePullPolicy: Always
          ports:
            - containerPort: 17171
              protocol: TCP
              name: grpc-test
          env:
            - name: GRPC_XDS_EXPERIMENTAL_SECURITY_SUPPORT
              value: "true"
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          volumeMounts:
            - mountPath: /var/lib/dubbo/data
              name: dubbo-data
      volumes:
        - name: dubbo-data
          emptyDir: {}