//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: security/v1alpha3/ca.proto

package v1alpha3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DubboCertificateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Csr              string                 `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
	ValidityDuration int64                  `protobuf:"varint,2,opt,name=validity_duration,json=validityDuration,proto3" json:"validity_duration,omitempty"`
	Metadata         *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DubboCertificateRequest) Reset() {
	*x = DubboCertificateRequest{}
	mi := &file_security_v1alpha3_ca_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DubboCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DubboCertificateRequest) ProtoMessage() {}

func (x *DubboCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1alpha3_ca_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DubboCertificateRequest.ProtoReflect.Descriptor instead.
func (*DubboCertificateRequest) Descriptor() ([]byte, []int) {
	return file_security_v1alpha3_ca_proto_rawDescGZIP(), []int{0}
}

func (x *DubboCertificateRequest) GetCsr() string {
	if x != nil {
		return x.Csr
	}
	return ""
}

func (x *DubboCertificateRequest) GetValidityDuration() int64 {
	if x != nil {
		return x.ValidityDuration
	}
	return 0
}

func (x *DubboCertificateRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DubboCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertChain     []string               `protobuf:"bytes,1,rep,name=cert_chain,json=certChain,proto3" json:"cert_chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DubboCertificateResponse) Reset() {
	*x = DubboCertificateResponse{}
	mi := &file_security_v1alpha3_ca_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DubboCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DubboCertificateResponse) ProtoMessage() {}

func (x *DubboCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_v1alpha3_ca_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DubboCertificateResponse.ProtoReflect.Descriptor instead.
func (*DubboCertificateResponse) Descriptor() ([]byte, []int) {
	return file_security_v1alpha3_ca_proto_rawDescGZIP(), []int{1}
}

func (x *DubboCertificateResponse) GetCertChain() []string {
	if x != nil {
		return x.CertChain
	}
	return nil
}

var File_security_v1alpha3_ca_proto protoreflect.FileDescriptor

const file_security_v1alpha3_ca_proto_rawDesc = "" +
	"\n" +
	"\x1asecurity/v1alpha3/ca.proto\x12\rdubbo.v1.auth\x1a\x1cgoogle/protobuf/struct.proto\"\x8d\x01\n" +
	"\x17DubboCertificateRequest\x12\x10\n" +
	"\x03csr\x18\x01 \x01(\tR\x03csr\x12+\n" +
	"\x11validity_duration\x18\x02 \x01(\x03R\x10validityDuration\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"9\n" +
	"\x18DubboCertificateResponse\x12\x1d\n" +
	"\n" +
	"cert_chain\x18\x01 \x03(\tR\tcertChain2\x81\x01\n" +
	"\x17DubboCertificateService\x12f\n" +
	"\x11CreateCertificate\x12&.dubbo.v1.auth.DubboCertificateRequest\x1a'.dubbo.v1.auth.DubboCertificateResponse\"\x00B\x18Z\x16/api/security/v1alpha3b\x06proto3"

var (
	file_security_v1alpha3_ca_proto_rawDescOnce sync.Once
	file_security_v1alpha3_ca_proto_rawDescData []byte
)

func file_security_v1alpha3_ca_proto_rawDescGZIP() []byte {
	file_security_v1alpha3_ca_proto_rawDescOnce.Do(func() {
		file_security_v1alpha3_ca_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_v1alpha3_ca_proto_rawDesc), len(file_security_v1alpha3_ca_proto_rawDesc)))
	})
	return file_security_v1alpha3_ca_proto_rawDescData
}

var file_security_v1alpha3_ca_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_security_v1alpha3_ca_proto_goTypes = []any{
	(*DubboCertificateRequest)(nil),  // 0: dubbo.v1.auth.DubboCertificateRequest
	(*DubboCertificateResponse)(nil), // 1: dubbo.v1.auth.DubboCertificateResponse
	(*structpb.Struct)(nil),          // 2: google.protobuf.Struct
}
var file_security_v1alpha3_ca_proto_depIdxs = []int32{
	2, // 0: dubbo.v1.auth.DubboCertificateRequest.metadata:type_name -> google.protobuf.Struct
	0, // 1: dubbo.v1.auth.DubboCertificateService.CreateCertificate:input_type -> dubbo.v1.auth.DubboCertificateRequest
	1, // 2: dubbo.v1.auth.DubboCertificateService.CreateCertificate:output_type -> dubbo.v1.auth.DubboCertificateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_security_v1alpha3_ca_proto_init() }
func file_security_v1alpha3_ca_proto_init() {
	if File_security_v1alpha3_ca_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_v1alpha3_ca_proto_rawDesc), len(file_security_v1alpha3_ca_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_security_v1alpha3_ca_proto_goTypes,
		DependencyIndexes: file_security_v1alpha3_ca_proto_depIdxs,
		MessageInfos:      file_security_v1alpha3_ca_proto_msgTypes,
	}.Build()
	File_security_v1alpha3_ca_proto = out.File
	file_security_v1alpha3_ca_proto_goTypes = nil
	file_security_v1alpha3_ca_proto_depIdxs = nil
}
