// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha3

import (
	proto "google.golang.org/protobuf/proto"
)

// DeepCopyInto supports using DubboCertificateRequest within kubernetes types, where deepcopy-gen is used.
func (in *DubboCertificateRequest) DeepCopyInto(out *DubboCertificateRequest) {
	p := proto.Clone(in).(*DubboCertificateRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DubboCertificateRequest. Required by controller-gen.
func (in *DubboCertificateRequest) DeepCopy() *DubboCertificateRequest {
	if in == nil {
		return nil
	}
	out := new(DubboCertificateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DubboCertificateRequest. Required by controller-gen.
func (in *DubboCertificateRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DubboCertificateResponse within kubernetes types, where deepcopy-gen is used.
func (in *DubboCertificateResponse) DeepCopyInto(out *DubboCertificateResponse) {
	p := proto.Clone(in).(*DubboCertificateResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DubboCertificateResponse. Required by controller-gen.
func (in *DubboCertificateResponse) DeepCopy() *DubboCertificateResponse {
	if in == nil {
		return nil
	}
	out := new(DubboCertificateResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DubboCertificateResponse. Required by controller-gen.
func (in *DubboCertificateResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
