//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: security/v1alpha3/ca.proto

package v1alpha3

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DubboCertificateService_CreateCertificate_FullMethodName = "/dubbo.v1.auth.DubboCertificateService/CreateCertificate"
)

// DubboCertificateServiceClient is the client API for DubboCertificateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DubboCertificateServiceClient interface {
	CreateCertificate(ctx context.Context, in *DubboCertificateRequest, opts ...grpc.CallOption) (*DubboCertificateResponse, error)
}

type dubboCertificateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDubboCertificateServiceClient(cc grpc.ClientConnInterface) DubboCertificateServiceClient {
	return &dubboCertificateServiceClient{cc}
}

func (c *dubboCertificateServiceClient) CreateCertificate(ctx context.Context, in *DubboCertificateRequest, opts ...grpc.CallOption) (*DubboCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DubboCertificateResponse)
	err := c.cc.Invoke(ctx, DubboCertificateService_CreateCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DubboCertificateServiceServer is the server API for DubboCertificateService service.
// All implementations must embed UnimplementedDubboCertificateServiceServer
// for forward compatibility.
type DubboCertificateServiceServer interface {
	CreateCertificate(context.Context, *DubboCertificateRequest) (*DubboCertificateResponse, error)
	mustEmbedUnimplementedDubboCertificateServiceServer()
}

// UnimplementedDubboCertificateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDubboCertificateServiceServer struct{}

func (UnimplementedDubboCertificateServiceServer) CreateCertificate(context.Context, *DubboCertificateRequest) (*DubboCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCertificate not implemented")
}
func (UnimplementedDubboCertificateServiceServer) mustEmbedUnimplementedDubboCertificateServiceServer() {
}
func (UnimplementedDubboCertificateServiceServer) testEmbeddedByValue() {}

// UnsafeDubboCertificateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DubboCertificateServiceServer will
// result in compilation errors.
type UnsafeDubboCertificateServiceServer interface {
	mustEmbedUnimplementedDubboCertificateServiceServer()
}

func RegisterDubboCertificateServiceServer(s grpc.ServiceRegistrar, srv DubboCertificateServiceServer) {
	// If the following call pancis, it indicates UnimplementedDubboCertificateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DubboCertificateService_ServiceDesc, srv)
}

func _DubboCertificateService_CreateCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DubboCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DubboCertificateServiceServer).CreateCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DubboCertificateService_CreateCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DubboCertificateServiceServer).CreateCertificate(ctx, req.(*DubboCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DubboCertificateService_ServiceDesc is the grpc.ServiceDesc for DubboCertificateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DubboCertificateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dubbo.v1.auth.DubboCertificateService",
	HandlerType: (*DubboCertificateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCertificate",
			Handler:    _DubboCertificateService_CreateCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "security/v1alpha3/ca.proto",
}
