#!/bin/bash
set -e

NAMESPACE="grpc-proxyless"

echo "=== gRPC Proxyless 测试命令 ==="
echo ""

echo "=== 快速测试步骤 ==="
echo ""
echo "# 1. 重新构建 producer 镜像（代码已修改）"
echo "cd test/grpc-proxyless"
echo "docker build -f Dockerfile.producer -t mfordjody/grpc-producer:latest ."
echo "docker push mfordjody/grpc-producer:latest  # 如果需要推送到 registry"
echo ""
echo "# 2. 重启 producer deployment"
echo "kubectl rollout restart deployment/producer -n grpc-proxyless"
echo "kubectl rollout status deployment/producer -n grpc-proxyless"
echo ""
echo "# 3. 等待 pod 就绪"
echo "kubectl wait --for=condition=ready pod -l app=producer -n grpc-proxyless --timeout=60s"
echo ""
echo "# 4. 查看 producer 应用日志（观察连接状态和 RPC 调用）"
echo "kubectl logs -f -l app=producer -c app -n grpc-proxyless --tail=100"
echo ""
echo "# 5. 查看 producer xDS proxy 日志（观察 EDS 响应）"
echo "kubectl logs -f -l app=producer -c dubbo-proxy -n grpc-proxyless --tail=100 | grep -i 'xds\|eds\|connection'"
echo ""
echo "# 6. 测试 ForwardEcho（需要先启动 port-forward）"
echo "# 在另一个终端执行："
echo "kubectl port-forward -n grpc-proxyless \$(kubectl get pod -l app=producer -n grpc-proxyless -o jsonpath='{.items[0].metadata.name}') 17171:17171"
echo ""
echo "# 然后执行测试（注意：-d 参数必须在地址之前！）："
echo ""
echo "# 方法1: 直接使用 -d 参数（推荐）"
echo "grpcurl -plaintext -d '{\"url\": \"xds:///consumer.grpc-proxyless.svc.cluster.local:7070\", \"count\": 5}' localhost:17171 echo.EchoTestService/ForwardEcho"
echo ""
echo "# 方法2: 使用标准输入（如果方法1不行）"
echo "echo '{\"url\": \"xds:///consumer.grpc-proxyless.svc.cluster.local:7070\", \"count\": 5}' | grpcurl -plaintext -d @ localhost:17171 echo.EchoTestService/ForwardEcho"
echo ""
echo "# 方法3: 使用文件"
echo "cat > /tmp/request.json << 'JSON'"
echo "{\"url\": \"xds:///consumer.grpc-proxyless.svc.cluster.local:7070\", \"count\": 5}"
echo "JSON"
echo "grpcurl -plaintext -d @ /tmp/request.json localhost:17171 echo.EchoTestService/ForwardEcho"
echo ""
echo "# 7. 查看控制平面日志（检查 EDS 推送）"
echo "kubectl logs -f -l app=dubbod -n dubbo-system --tail=100 | grep -i 'eds\|endpoint\|consumer'"
echo ""
