# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

podLabels:
  customLableA: Aaaaa
imageRenderer:
  enabled: true
  env:
    RENDERING_ARGS: --disable-gpu,--window-size=1280x758
    RENDERING_MODE: clustered
  podLabels:
    customLableB: Bbbbb
  networkPolicy:
    limitIngress: true
    limitEgress: true
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 50Mi
  extraVolumes:
    - name: empty-renderer-volume
      emtpyDir: {}
  extraVolumeMounts:
    - mountPath: /tmp/renderer
      name: empty-renderer-volume
  extraConfigmapMounts:
    - name: renderer-config
      mountPath: /usr/src/app/config.json
      subPath: renderer-config.json
      configMap: image-renderer-config
  extraSecretMounts:
    - name: renderer-certificate
      mountPath: /usr/src/app/certs/
      secretName: image-renderer-certificate
      readOnly: true

extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: image-renderer-config
    data:
      renderer-config.json: |
        {
          "service": {
            "host": null,
            "port": 8081,
            "protocol": "http",
            "certFile": "",
            "certKey": "",

            "metrics": {
              "enabled": true,
              "collectDefaultMetrics": true,
              "requestDurationBuckets": [1, 5, 7, 9, 11, 13, 15, 20, 30]
            },

            "logging": {
              "level": "info",
              "console": {
                "json": true,
                "colorize": false
              }
            },

            "security": {
              "authToken": "-"
            }
          },
          "rendering": {
            "chromeBin": null,
            "args": ["--no-sandbox", "--disable-gpu"],
            "ignoresHttpsErrors": false,

            "timezone": null,
            "acceptLanguage": null,
            "width": 1000,
            "height": 500,
            "deviceScaleFactor": 1,
            "maxWidth": 3080,
            "maxHeight": 3000,
            "maxDeviceScaleFactor": 4,
            "pageZoomLevel": 1,
            "headed": false,

            "mode": "default",
            "emulateNetworkConditions": false,
            "clustering": {
              "monitor": false,
              "mode": "browser",
              "maxConcurrency": 5,
              "timeout": 30
            },

            "verboseLogging": false,
            "dumpio": false,
            "timingMetrics": false
          }
        }
  - apiVersion: v1
    kind: Secret
    metadata:
      name: image-renderer-certificate
    type: Opaque
    data:
      # Decodes to 'PLACEHOLDER CERTIFICATE'
      not-a-real-certificate: UExBQ0VIT0xERVIgQ0VSVElGSUNBVEU=
