//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: values_types.proto

package apis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GUIConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int64                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	NodePort      int64                  `protobuf:"varint,2,opt,name=nodePort,proto3" json:"nodePort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GUIConfig) Reset() {
	*x = GUIConfig{}
	mi := &file_values_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GUIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GUIConfig) ProtoMessage() {}

func (x *GUIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_values_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GUIConfig.ProtoReflect.Descriptor instead.
func (*GUIConfig) Descriptor() ([]byte, []int) {
	return file_values_types_proto_rawDescGZIP(), []int{0}
}

func (x *GUIConfig) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GUIConfig) GetNodePort() int64 {
	if x != nil {
		return x.NodePort
	}
	return 0
}

type ProxyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterDomain string                 `protobuf:"bytes,1,opt,name=clusterDomain,proto3" json:"clusterDomain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyConfig) Reset() {
	*x = ProxyConfig{}
	mi := &file_values_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConfig) ProtoMessage() {}

func (x *ProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_values_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConfig.ProtoReflect.Descriptor instead.
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return file_values_types_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyConfig) GetClusterDomain() string {
	if x != nil {
		return x.ClusterDomain
	}
	return ""
}

type ProxylessConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cni           *MeshCNIConfig         `protobuf:"bytes,1,opt,name=cni,proto3" json:"cni,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxylessConfig) Reset() {
	*x = ProxylessConfig{}
	mi := &file_values_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxylessConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxylessConfig) ProtoMessage() {}

func (x *ProxylessConfig) ProtoReflect() protoreflect.Message {
	mi := &file_values_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxylessConfig.ProtoReflect.Descriptor instead.
func (*ProxylessConfig) Descriptor() ([]byte, []int) {
	return file_values_types_proto_rawDescGZIP(), []int{2}
}

func (x *ProxylessConfig) GetCni() *MeshCNIConfig {
	if x != nil {
		return x.Cni
	}
	return nil
}

type MeshCNIConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Enabled           bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Image             string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	BinDir            string                 `protobuf:"bytes,3,opt,name=binDir,proto3" json:"binDir,omitempty"`
	ConfDir           string                 `protobuf:"bytes,4,opt,name=confDir,proto3" json:"confDir,omitempty"`
	StateDir          string                 `protobuf:"bytes,5,opt,name=stateDir,proto3" json:"stateDir,omitempty"`
	GrpcInboundPort   int64                  `protobuf:"varint,6,opt,name=grpcInboundPort,proto3" json:"grpcInboundPort,omitempty"`
	ManagedLabel      string                 `protobuf:"bytes,7,opt,name=managedLabel,proto3" json:"managedLabel,omitempty"`
	ManagedLabelValue string                 `protobuf:"bytes,8,opt,name=managedLabelValue,proto3" json:"managedLabelValue,omitempty"`
	IptablesPath      string                 `protobuf:"bytes,9,opt,name=iptablesPath,proto3" json:"iptablesPath,omitempty"`
	IpsetPath         string                 `protobuf:"bytes,10,opt,name=ipsetPath,proto3" json:"ipsetPath,omitempty"`
	RefreshInterval   string                 `protobuf:"bytes,11,opt,name=refreshInterval,proto3" json:"refreshInterval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MeshCNIConfig) Reset() {
	*x = MeshCNIConfig{}
	mi := &file_values_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshCNIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshCNIConfig) ProtoMessage() {}

func (x *MeshCNIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_values_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshCNIConfig.ProtoReflect.Descriptor instead.
func (*MeshCNIConfig) Descriptor() ([]byte, []int) {
	return file_values_types_proto_rawDescGZIP(), []int{3}
}

func (x *MeshCNIConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MeshCNIConfig) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MeshCNIConfig) GetBinDir() string {
	if x != nil {
		return x.BinDir
	}
	return ""
}

func (x *MeshCNIConfig) GetConfDir() string {
	if x != nil {
		return x.ConfDir
	}
	return ""
}

func (x *MeshCNIConfig) GetStateDir() string {
	if x != nil {
		return x.StateDir
	}
	return ""
}

func (x *MeshCNIConfig) GetGrpcInboundPort() int64 {
	if x != nil {
		return x.GrpcInboundPort
	}
	return 0
}

func (x *MeshCNIConfig) GetManagedLabel() string {
	if x != nil {
		return x.ManagedLabel
	}
	return ""
}

func (x *MeshCNIConfig) GetManagedLabelValue() string {
	if x != nil {
		return x.ManagedLabelValue
	}
	return ""
}

func (x *MeshCNIConfig) GetIptablesPath() string {
	if x != nil {
		return x.IptablesPath
	}
	return ""
}

func (x *MeshCNIConfig) GetIpsetPath() string {
	if x != nil {
		return x.IpsetPath
	}
	return ""
}

func (x *MeshCNIConfig) GetRefreshInterval() string {
	if x != nil {
		return x.RefreshInterval
	}
	return ""
}

type GlobalConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Proxy            *ProxyConfig           `protobuf:"bytes,1,opt,name=proxy,proto3" json:"proxy,omitempty"`
	StatusPort       int64                  `protobuf:"varint,2,opt,name=statusPort,proto3" json:"statusPort,omitempty"`
	Gui              *GUIConfig             `protobuf:"bytes,3,opt,name=gui,proto3" json:"gui,omitempty"`
	ConfigValidation bool                   `protobuf:"varint,4,opt,name=configValidation,proto3" json:"configValidation,omitempty"`
	Multicluster     *MulticlusterConfig    `protobuf:"bytes,5,opt,name=multicluster,proto3" json:"multicluster,omitempty"`
	Proxyless        *ProxylessConfig       `protobuf:"bytes,6,opt,name=proxyless,proto3" json:"proxyless,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GlobalConfig) Reset() {
	*x = GlobalConfig{}
	mi := &file_values_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalConfig) ProtoMessage() {}

func (x *GlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_values_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalConfig.ProtoReflect.Descriptor instead.
func (*GlobalConfig) Descriptor() ([]byte, []int) {
	return file_values_types_proto_rawDescGZIP(), []int{4}
}

func (x *GlobalConfig) GetProxy() *ProxyConfig {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *GlobalConfig) GetStatusPort() int64 {
	if x != nil {
		return x.StatusPort
	}
	return 0
}

func (x *GlobalConfig) GetGui() *GUIConfig {
	if x != nil {
		return x.Gui
	}
	return nil
}

func (x *GlobalConfig) GetConfigValidation() bool {
	if x != nil {
		return x.ConfigValidation
	}
	return false
}

func (x *GlobalConfig) GetMulticluster() *MulticlusterConfig {
	if x != nil {
		return x.Multicluster
	}
	return nil
}

func (x *GlobalConfig) GetProxyless() *ProxylessConfig {
	if x != nil {
		return x.Proxyless
	}
	return nil
}

type RemoteAccessConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ServiceType      string                 `protobuf:"bytes,2,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	XdsPort          int64                  `protobuf:"varint,3,opt,name=xdsPort,proto3" json:"xdsPort,omitempty"`
	WebhookPort      int64                  `protobuf:"varint,4,opt,name=webhookPort,proto3" json:"webhookPort,omitempty"`
	CertificateHosts []string               `protobuf:"bytes,5,rep,name=certificateHosts,proto3" json:"certificateHosts,omitempty"`
	GrpcPort         int64                  `protobuf:"varint,6,opt,name=grpcPort,proto3" json:"grpcPort,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoteAccessConfig) Reset() {
	*x = RemoteAccessConfig{}
	mi := &file_values_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteAccessConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteAccessConfig) ProtoMessage() {}

func (x *RemoteAccessConfig) ProtoReflect() protoreflect.Message {
	mi := &file_values_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteAccessConfig.ProtoReflect.Descriptor instead.
func (*RemoteAccessConfig) Descriptor() ([]byte, []int) {
	return file_values_types_proto_rawDescGZIP(), []int{5}
}

func (x *RemoteAccessConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RemoteAccessConfig) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *RemoteAccessConfig) GetXdsPort() int64 {
	if x != nil {
		return x.XdsPort
	}
	return 0
}

func (x *RemoteAccessConfig) GetWebhookPort() int64 {
	if x != nil {
		return x.WebhookPort
	}
	return 0
}

func (x *RemoteAccessConfig) GetCertificateHosts() []string {
	if x != nil {
		return x.CertificateHosts
	}
	return nil
}

func (x *RemoteAccessConfig) GetGrpcPort() int64 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

type EastWestGatewayEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int64                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EastWestGatewayEndpoint) Reset() {
	*x = EastWestGatewayEndpoint{}
	mi := &file_values_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EastWestGatewayEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EastWestGatewayEndpoint) ProtoMessage() {}

func (x *EastWestGatewayEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_values_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EastWestGatewayEndpoint.ProtoReflect.Descriptor instead.
func (*EastWestGatewayEndpoint) Descriptor() ([]byte, []int) {
	return file_values_types_proto_rawDescGZIP(), []int{6}
}

func (x *EastWestGatewayEndpoint) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *EastWestGatewayEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EastWestGatewayEndpoint) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

type EastWestGatewayConfig struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Enabled       bool                       `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ServiceType   string                     `protobuf:"bytes,2,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Port          int64                      `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	TargetPort    int64                      `protobuf:"varint,4,opt,name=targetPort,proto3" json:"targetPort,omitempty"`
	NodePort      int64                      `protobuf:"varint,5,opt,name=nodePort,proto3" json:"nodePort,omitempty"`
	Gateways      []*EastWestGatewayEndpoint `protobuf:"bytes,6,rep,name=gateways,proto3" json:"gateways,omitempty"`
	XdsAddress    string                     `protobuf:"bytes,7,opt,name=xdsAddress,proto3" json:"xdsAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EastWestGatewayConfig) Reset() {
	*x = EastWestGatewayConfig{}
	mi := &file_values_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EastWestGatewayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EastWestGatewayConfig) ProtoMessage() {}

func (x *EastWestGatewayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_values_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EastWestGatewayConfig.ProtoReflect.Descriptor instead.
func (*EastWestGatewayConfig) Descriptor() ([]byte, []int) {
	return file_values_types_proto_rawDescGZIP(), []int{7}
}

func (x *EastWestGatewayConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EastWestGatewayConfig) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *EastWestGatewayConfig) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EastWestGatewayConfig) GetTargetPort() int64 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *EastWestGatewayConfig) GetNodePort() int64 {
	if x != nil {
		return x.NodePort
	}
	return 0
}

func (x *EastWestGatewayConfig) GetGateways() []*EastWestGatewayEndpoint {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *EastWestGatewayConfig) GetXdsAddress() string {
	if x != nil {
		return x.XdsAddress
	}
	return ""
}

type MulticlusterConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RemoteAccess    *RemoteAccessConfig    `protobuf:"bytes,1,opt,name=remoteAccess,proto3" json:"remoteAccess,omitempty"`
	EastWestGateway *EastWestGatewayConfig `protobuf:"bytes,2,opt,name=eastWestGateway,proto3" json:"eastWestGateway,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MulticlusterConfig) Reset() {
	*x = MulticlusterConfig{}
	mi := &file_values_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MulticlusterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulticlusterConfig) ProtoMessage() {}

func (x *MulticlusterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_values_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulticlusterConfig.ProtoReflect.Descriptor instead.
func (*MulticlusterConfig) Descriptor() ([]byte, []int) {
	return file_values_types_proto_rawDescGZIP(), []int{8}
}

func (x *MulticlusterConfig) GetRemoteAccess() *RemoteAccessConfig {
	if x != nil {
		return x.RemoteAccess
	}
	return nil
}

func (x *MulticlusterConfig) GetEastWestGateway() *EastWestGatewayConfig {
	if x != nil {
		return x.EastWestGateway
	}
	return nil
}

type Values struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Global configuration for dubbo components.
	Global *GlobalConfig `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	// Revision for rendered control plane resources.
	Revision      string `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Values) Reset() {
	*x = Values{}
	mi := &file_values_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Values) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Values) ProtoMessage() {}

func (x *Values) ProtoReflect() protoreflect.Message {
	mi := &file_values_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Values.ProtoReflect.Descriptor instead.
func (*Values) Descriptor() ([]byte, []int) {
	return file_values_types_proto_rawDescGZIP(), []int{9}
}

func (x *Values) GetGlobal() *GlobalConfig {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *Values) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

// IntOrString is a type that can hold an int32 or a string.  When used in
// JSON or YAML marshalling and unmarshalling, it produces or consumes the
// inner type.  This allows you to have, for example, a JSON field that can
// accept a name or number.
// TODO: Rename to Int32OrString
//
// +protobuf=true
// +protobuf.options.(gogoproto.goproto_stringer)=false
// +k8s:openapi-gen=true
type IntOrString struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          int64                   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	IntVal        *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=intVal,proto3" json:"intVal,omitempty"`
	StrVal        *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=strVal,proto3" json:"strVal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntOrString) Reset() {
	*x = IntOrString{}
	mi := &file_values_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntOrString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntOrString) ProtoMessage() {}

func (x *IntOrString) ProtoReflect() protoreflect.Message {
	mi := &file_values_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntOrString.ProtoReflect.Descriptor instead.
func (*IntOrString) Descriptor() ([]byte, []int) {
	return file_values_types_proto_rawDescGZIP(), []int{10}
}

func (x *IntOrString) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *IntOrString) GetIntVal() *wrapperspb.Int32Value {
	if x != nil {
		return x.IntVal
	}
	return nil
}

func (x *IntOrString) GetStrVal() *wrapperspb.StringValue {
	if x != nil {
		return x.StrVal
	}
	return nil
}

var File_values_types_proto protoreflect.FileDescriptor

const file_values_types_proto_rawDesc = "" +
	"\n" +
	"\x12values_types.proto\x12\x17dubbo.operator.v1alpha1\x1a\x1egoogle/protobuf/wrappers.proto\";\n" +
	"\tGUIConfig\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x03R\x04port\x12\x1a\n" +
	"\bnodePort\x18\x02 \x01(\x03R\bnodePort\"3\n" +
	"\vProxyConfig\x12$\n" +
	"\rclusterDomain\x18\x01 \x01(\tR\rclusterDomain\"K\n" +
	"\x0fProxylessConfig\x128\n" +
	"\x03cni\x18\x01 \x01(\v2&.dubbo.operator.v1alpha1.MeshCNIConfigR\x03cni\"\xf5\x02\n" +
	"\rMeshCNIConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x16\n" +
	"\x06binDir\x18\x03 \x01(\tR\x06binDir\x12\x18\n" +
	"\aconfDir\x18\x04 \x01(\tR\aconfDir\x12\x1a\n" +
	"\bstateDir\x18\x05 \x01(\tR\bstateDir\x12(\n" +
	"\x0fgrpcInboundPort\x18\x06 \x01(\x03R\x0fgrpcInboundPort\x12\"\n" +
	"\fmanagedLabel\x18\a \x01(\tR\fmanagedLabel\x12,\n" +
	"\x11managedLabelValue\x18\b \x01(\tR\x11managedLabelValue\x12\"\n" +
	"\fiptablesPath\x18\t \x01(\tR\fiptablesPath\x12\x1c\n" +
	"\tipsetPath\x18\n" +
	" \x01(\tR\tipsetPath\x12(\n" +
	"\x0frefreshInterval\x18\v \x01(\tR\x0frefreshInterval\"\xe5\x02\n" +
	"\fGlobalConfig\x12:\n" +
	"\x05proxy\x18\x01 \x01(\v2$.dubbo.operator.v1alpha1.ProxyConfigR\x05proxy\x12\x1e\n" +
	"\n" +
	"statusPort\x18\x02 \x01(\x03R\n" +
	"statusPort\x124\n" +
	"\x03gui\x18\x03 \x01(\v2\".dubbo.operator.v1alpha1.GUIConfigR\x03gui\x12*\n" +
	"\x10configValidation\x18\x04 \x01(\bR\x10configValidation\x12O\n" +
	"\fmulticluster\x18\x05 \x01(\v2+.dubbo.operator.v1alpha1.MulticlusterConfigR\fmulticluster\x12F\n" +
	"\tproxyless\x18\x06 \x01(\v2(.dubbo.operator.v1alpha1.ProxylessConfigR\tproxyless\"\xd4\x01\n" +
	"\x12RemoteAccessConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12 \n" +
	"\vserviceType\x18\x02 \x01(\tR\vserviceType\x12\x18\n" +
	"\axdsPort\x18\x03 \x01(\x03R\axdsPort\x12 \n" +
	"\vwebhookPort\x18\x04 \x01(\x03R\vwebhookPort\x12*\n" +
	"\x10certificateHosts\x18\x05 \x03(\tR\x10certificateHosts\x12\x1a\n" +
	"\bgrpcPort\x18\x06 \x01(\x03R\bgrpcPort\"i\n" +
	"\x17EastWestGatewayEndpoint\x12 \n" +
	"\vclusterName\x18\x01 \x01(\tR\vclusterName\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x03R\x04port\"\x91\x02\n" +
	"\x15EastWestGatewayConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12 \n" +
	"\vserviceType\x18\x02 \x01(\tR\vserviceType\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x03R\x04port\x12\x1e\n" +
	"\n" +
	"targetPort\x18\x04 \x01(\x03R\n" +
	"targetPort\x12\x1a\n" +
	"\bnodePort\x18\x05 \x01(\x03R\bnodePort\x12L\n" +
	"\bgateways\x18\x06 \x03(\v20.dubbo.operator.v1alpha1.EastWestGatewayEndpointR\bgateways\x12\x1e\n" +
	"\n" +
	"xdsAddress\x18\a \x01(\tR\n" +
	"xdsAddress\"\xbf\x01\n" +
	"\x12MulticlusterConfig\x12O\n" +
	"\fremoteAccess\x18\x01 \x01(\v2+.dubbo.operator.v1alpha1.RemoteAccessConfigR\fremoteAccess\x12X\n" +
	"\x0feastWestGateway\x18\x02 \x01(\v2..dubbo.operator.v1alpha1.EastWestGatewayConfigR\x0feastWestGateway\"c\n" +
	"\x06Values\x12=\n" +
	"\x06global\x18\x01 \x01(\v2%.dubbo.operator.v1alpha1.GlobalConfigR\x06global\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\"\x8c\x01\n" +
	"\vIntOrString\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x03R\x04type\x123\n" +
	"\x06intVal\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x06intVal\x124\n" +
	"\x06strVal\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x06strValB*Z(dubbo.apache.org/dubbo/operator/pkg/apisb\x06proto3"

var (
	file_values_types_proto_rawDescOnce sync.Once
	file_values_types_proto_rawDescData []byte
)

func file_values_types_proto_rawDescGZIP() []byte {
	file_values_types_proto_rawDescOnce.Do(func() {
		file_values_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_values_types_proto_rawDesc), len(file_values_types_proto_rawDesc)))
	})
	return file_values_types_proto_rawDescData
}

var file_values_types_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_values_types_proto_goTypes = []any{
	(*GUIConfig)(nil),               // 0: dubbo.operator.v1alpha1.GUIConfig
	(*ProxyConfig)(nil),             // 1: dubbo.operator.v1alpha1.ProxyConfig
	(*ProxylessConfig)(nil),         // 2: dubbo.operator.v1alpha1.ProxylessConfig
	(*MeshCNIConfig)(nil),           // 3: dubbo.operator.v1alpha1.MeshCNIConfig
	(*GlobalConfig)(nil),            // 4: dubbo.operator.v1alpha1.GlobalConfig
	(*RemoteAccessConfig)(nil),      // 5: dubbo.operator.v1alpha1.RemoteAccessConfig
	(*EastWestGatewayEndpoint)(nil), // 6: dubbo.operator.v1alpha1.EastWestGatewayEndpoint
	(*EastWestGatewayConfig)(nil),   // 7: dubbo.operator.v1alpha1.EastWestGatewayConfig
	(*MulticlusterConfig)(nil),      // 8: dubbo.operator.v1alpha1.MulticlusterConfig
	(*Values)(nil),                  // 9: dubbo.operator.v1alpha1.Values
	(*IntOrString)(nil),             // 10: dubbo.operator.v1alpha1.IntOrString
	(*wrapperspb.Int32Value)(nil),   // 11: google.protobuf.Int32Value
	(*wrapperspb.StringValue)(nil),  // 12: google.protobuf.StringValue
}
var file_values_types_proto_depIdxs = []int32{
	3,  // 0: dubbo.operator.v1alpha1.ProxylessConfig.cni:type_name -> dubbo.operator.v1alpha1.MeshCNIConfig
	1,  // 1: dubbo.operator.v1alpha1.GlobalConfig.proxy:type_name -> dubbo.operator.v1alpha1.ProxyConfig
	0,  // 2: dubbo.operator.v1alpha1.GlobalConfig.gui:type_name -> dubbo.operator.v1alpha1.GUIConfig
	8,  // 3: dubbo.operator.v1alpha1.GlobalConfig.multicluster:type_name -> dubbo.operator.v1alpha1.MulticlusterConfig
	2,  // 4: dubbo.operator.v1alpha1.GlobalConfig.proxyless:type_name -> dubbo.operator.v1alpha1.ProxylessConfig
	6,  // 5: dubbo.operator.v1alpha1.EastWestGatewayConfig.gateways:type_name -> dubbo.operator.v1alpha1.EastWestGatewayEndpoint
	5,  // 6: dubbo.operator.v1alpha1.MulticlusterConfig.remoteAccess:type_name -> dubbo.operator.v1alpha1.RemoteAccessConfig
	7,  // 7: dubbo.operator.v1alpha1.MulticlusterConfig.eastWestGateway:type_name -> dubbo.operator.v1alpha1.EastWestGatewayConfig
	4,  // 8: dubbo.operator.v1alpha1.Values.global:type_name -> dubbo.operator.v1alpha1.GlobalConfig
	11, // 9: dubbo.operator.v1alpha1.IntOrString.intVal:type_name -> google.protobuf.Int32Value
	12, // 10: dubbo.operator.v1alpha1.IntOrString.strVal:type_name -> google.protobuf.StringValue
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_values_types_proto_init() }
func file_values_types_proto_init() {
	if File_values_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_values_types_proto_rawDesc), len(file_values_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_values_types_proto_goTypes,
		DependencyIndexes: file_values_types_proto_depIdxs,
		MessageInfos:      file_values_types_proto_msgTypes,
	}.Build()
	File_values_types_proto = out.File
	file_values_types_proto_goTypes = nil
	file_values_types_proto_depIdxs = nil
}
