# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.24-alpine AS builder

WORKDIR /build

RUN apk add --no-cache protobuf

COPY go.mod go.sum ./
RUN go mod download

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

ENV PATH=$PATH:/go/bin:/root/go/bin

COPY proto/echo.proto ./proto/
RUN protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    proto/echo.proto

COPY consumer/ ./consumer/

ARG GOOS=linux
ARG GOARCH=amd64
RUN GOOS=${GOOS} GOARCH=${GOARCH} CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' -o /build/grpc-consumer ./consumer/

FROM alpine:latest
RUN apk update && \
    apk --no-cache add ca-certificates tzdata || \
    (sleep 2 && apk update && apk --no-cache add ca-certificates tzdata)
WORKDIR /app

COPY --from=builder /build/grpc-consumer /usr/local/bin/grpc-consumer
RUN chmod +x /usr/local/bin/grpc-consumer

ENTRYPOINT ["/usr/local/bin/grpc-consumer"]
