FROM golang:1.24-alpine AS builder

WORKDIR /build

RUN apk add --no-cache protobuf

COPY go.mod go.sum ./
RUN go mod download

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

ENV PATH=$PATH:/go/bin:/root/go/bin

COPY proto/echo.proto ./proto/
RUN protoc --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    proto/echo.proto

COPY producer/ ./producer/

ARG GOOS=linux
ARG GOARCH=amd64
RUN GOOS=${GOOS} GOARCH=${GOARCH} CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' -o /build/grpc-producer ./producer/

FROM alpine:latest
RUN apk update && \
    apk --no-cache add ca-certificates tzdata || \
    (sleep 2 && apk update && apk --no-cache add ca-certificates tzdata)
WORKDIR /app

COPY --from=builder /build/grpc-producer /usr/local/bin/grpc-producer
RUN chmod +x /usr/local/bin/grpc-producer

ENTRYPOINT ["/usr/local/bin/grpc-producer"]
