//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: networking/v1alpha3/destination_rule.proto

// $schema: dubbo.networking.v1alpha3.DestinationRule
// $title: Destination Rule

package v1alpha3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientTLSSettings_TLSmode int32

const (
	ClientTLSSettings_DISABLE ClientTLSSettings_TLSmode = 0
	// TODO Not yet implemented
	ClientTLSSettings_MUTUAL       ClientTLSSettings_TLSmode = 1
	ClientTLSSettings_DUBBO_MUTUAL ClientTLSSettings_TLSmode = 2
)

// Enum value maps for ClientTLSSettings_TLSmode.
var (
	ClientTLSSettings_TLSmode_name = map[int32]string{
		0: "DISABLE",
		1: "MUTUAL",
		2: "DUBBO_MUTUAL",
	}
	ClientTLSSettings_TLSmode_value = map[string]int32{
		"DISABLE":      0,
		"MUTUAL":       1,
		"DUBBO_MUTUAL": 2,
	}
)

func (x ClientTLSSettings_TLSmode) Enum() *ClientTLSSettings_TLSmode {
	p := new(ClientTLSSettings_TLSmode)
	*p = x
	return p
}

func (x ClientTLSSettings_TLSmode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientTLSSettings_TLSmode) Descriptor() protoreflect.EnumDescriptor {
	return file_networking_v1alpha3_destination_rule_proto_enumTypes[0].Descriptor()
}

func (ClientTLSSettings_TLSmode) Type() protoreflect.EnumType {
	return &file_networking_v1alpha3_destination_rule_proto_enumTypes[0]
}

func (x ClientTLSSettings_TLSmode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientTLSSettings_TLSmode.Descriptor instead.
func (ClientTLSSettings_TLSmode) EnumDescriptor() ([]byte, []int) {
	return file_networking_v1alpha3_destination_rule_proto_rawDescGZIP(), []int{3, 0}
}

// DestinationRule defines policies that apply to traffic intended for a service
// after routing has occurred.
//
// <!-- crd generation tags
// +cue-gen:DestinationRule:groupName:networking.dubbo.apache.org
// +cue-gen:DestinationRule:versions:v1alpha3
// +cue-gen:DestinationRule:annotations:helm.sh/resource-policy=keep
// +cue-gen:DestinationRule:labels:app=dubbo,chart=dubbo,heritage=Tiller,release=dubbo
// +cue-gen:DestinationRule:subresource:status
// +cue-gen:DestinationRule:scope:Namespaced
// +cue-gen:DestinationRule:resource:categories=dubbo,networking,shortNames=dr
// +cue-gen:DestinationRule:printerColumn:name=Host,type=string,JSONPath=.spec.host,description="The name of a service from the service registry"
// +cue-gen:DestinationRule:printerColumn:name=Age,type=date,JSONPath=.metadata.creationTimestamp,description="CreationTimestamp is a timestamp
// representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
// Populated by the system. Read-only. Null for lists. For more information, see [Kubernetes API Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata)"
// +cue-gen:DestinationRule:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.dubbo.apache.org/v1alpha3
// +genclient
// +k8s:deepcopy-gen=true
// -->
type DestinationRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	TrafficPolicy *TrafficPolicy         `protobuf:"bytes,2,opt,name=traffic_policy,json=trafficPolicy,proto3" json:"traffic_policy,omitempty"`
	Subsets       []*Subset              `protobuf:"bytes,3,rep,name=subsets,proto3" json:"subsets,omitempty"`
	ExportTo      []string               `protobuf:"bytes,4,rep,name=export_to,json=exportTo,proto3" json:"export_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestinationRule) Reset() {
	*x = DestinationRule{}
	mi := &file_networking_v1alpha3_destination_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestinationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationRule) ProtoMessage() {}

func (x *DestinationRule) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_destination_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationRule.ProtoReflect.Descriptor instead.
func (*DestinationRule) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_destination_rule_proto_rawDescGZIP(), []int{0}
}

func (x *DestinationRule) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DestinationRule) GetTrafficPolicy() *TrafficPolicy {
	if x != nil {
		return x.TrafficPolicy
	}
	return nil
}

func (x *DestinationRule) GetSubsets() []*Subset {
	if x != nil {
		return x.Subsets
	}
	return nil
}

func (x *DestinationRule) GetExportTo() []string {
	if x != nil {
		return x.ExportTo
	}
	return nil
}

type TrafficPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tls           *ClientTLSSettings     `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficPolicy) Reset() {
	*x = TrafficPolicy{}
	mi := &file_networking_v1alpha3_destination_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficPolicy) ProtoMessage() {}

func (x *TrafficPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_destination_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficPolicy.ProtoReflect.Descriptor instead.
func (*TrafficPolicy) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_destination_rule_proto_rawDescGZIP(), []int{1}
}

func (x *TrafficPolicy) GetTls() *ClientTLSSettings {
	if x != nil {
		return x.Tls
	}
	return nil
}

type Subset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TrafficPolicy *TrafficPolicy         `protobuf:"bytes,3,opt,name=traffic_policy,json=trafficPolicy,proto3" json:"traffic_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subset) Reset() {
	*x = Subset{}
	mi := &file_networking_v1alpha3_destination_rule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subset) ProtoMessage() {}

func (x *Subset) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_destination_rule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subset.ProtoReflect.Descriptor instead.
func (*Subset) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_destination_rule_proto_rawDescGZIP(), []int{2}
}

func (x *Subset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subset) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Subset) GetTrafficPolicy() *TrafficPolicy {
	if x != nil {
		return x.TrafficPolicy
	}
	return nil
}

type ClientTLSSettings struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Mode          ClientTLSSettings_TLSmode `protobuf:"varint,1,opt,name=mode,proto3,enum=dubbo.networking.v1alpha3.ClientTLSSettings_TLSmode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientTLSSettings) Reset() {
	*x = ClientTLSSettings{}
	mi := &file_networking_v1alpha3_destination_rule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTLSSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTLSSettings) ProtoMessage() {}

func (x *ClientTLSSettings) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_destination_rule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTLSSettings.ProtoReflect.Descriptor instead.
func (*ClientTLSSettings) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_destination_rule_proto_rawDescGZIP(), []int{3}
}

func (x *ClientTLSSettings) GetMode() ClientTLSSettings_TLSmode {
	if x != nil {
		return x.Mode
	}
	return ClientTLSSettings_DISABLE
}

var File_networking_v1alpha3_destination_rule_proto protoreflect.FileDescriptor

const file_networking_v1alpha3_destination_rule_proto_rawDesc = "" +
	"\n" +
	"*networking/v1alpha3/destination_rule.proto\x12\x19dubbo.networking.v1alpha3\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a)networking/v1alpha3/virtual_service.proto\"\xd6\x01\n" +
	"\x0fDestinationRule\x12\x18\n" +
	"\x04host\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04host\x12O\n" +
	"\x0etraffic_policy\x18\x02 \x01(\v2(.dubbo.networking.v1alpha3.TrafficPolicyR\rtrafficPolicy\x12;\n" +
	"\asubsets\x18\x03 \x03(\v2!.dubbo.networking.v1alpha3.SubsetR\asubsets\x12\x1b\n" +
	"\texport_to\x18\x04 \x03(\tR\bexportTo\"O\n" +
	"\rTrafficPolicy\x12>\n" +
	"\x03tls\x18\x04 \x01(\v2,.dubbo.networking.v1alpha3.ClientTLSSettingsR\x03tls\"\xf5\x01\n" +
	"\x06Subset\x12\x18\n" +
	"\x04name\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04name\x12E\n" +
	"\x06labels\x18\x02 \x03(\v2-.dubbo.networking.v1alpha3.Subset.LabelsEntryR\x06labels\x12O\n" +
	"\x0etraffic_policy\x18\x03 \x01(\v2(.dubbo.networking.v1alpha3.TrafficPolicyR\rtrafficPolicy\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\x11ClientTLSSettings\x12H\n" +
	"\x04mode\x18\x01 \x01(\x0e24.dubbo.networking.v1alpha3.ClientTLSSettings.TLSmodeR\x04mode\"4\n" +
	"\aTLSmode\x12\v\n" +
	"\aDISABLE\x10\x00\x12\n" +
	"\n" +
	"\x06MUTUAL\x10\x01\x12\x10\n" +
	"\fDUBBO_MUTUAL\x10\x02B\x1aZ\x18/api/networking/v1alpha3b\x06proto3"

var (
	file_networking_v1alpha3_destination_rule_proto_rawDescOnce sync.Once
	file_networking_v1alpha3_destination_rule_proto_rawDescData []byte
)

func file_networking_v1alpha3_destination_rule_proto_rawDescGZIP() []byte {
	file_networking_v1alpha3_destination_rule_proto_rawDescOnce.Do(func() {
		file_networking_v1alpha3_destination_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_destination_rule_proto_rawDesc), len(file_networking_v1alpha3_destination_rule_proto_rawDesc)))
	})
	return file_networking_v1alpha3_destination_rule_proto_rawDescData
}

var file_networking_v1alpha3_destination_rule_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_networking_v1alpha3_destination_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_networking_v1alpha3_destination_rule_proto_goTypes = []any{
	(ClientTLSSettings_TLSmode)(0), // 0: dubbo.networking.v1alpha3.ClientTLSSettings.TLSmode
	(*DestinationRule)(nil),        // 1: dubbo.networking.v1alpha3.DestinationRule
	(*TrafficPolicy)(nil),          // 2: dubbo.networking.v1alpha3.TrafficPolicy
	(*Subset)(nil),                 // 3: dubbo.networking.v1alpha3.Subset
	(*ClientTLSSettings)(nil),      // 4: dubbo.networking.v1alpha3.ClientTLSSettings
	nil,                            // 5: dubbo.networking.v1alpha3.Subset.LabelsEntry
}
var file_networking_v1alpha3_destination_rule_proto_depIdxs = []int32{
	2, // 0: dubbo.networking.v1alpha3.DestinationRule.traffic_policy:type_name -> dubbo.networking.v1alpha3.TrafficPolicy
	3, // 1: dubbo.networking.v1alpha3.DestinationRule.subsets:type_name -> dubbo.networking.v1alpha3.Subset
	4, // 2: dubbo.networking.v1alpha3.TrafficPolicy.tls:type_name -> dubbo.networking.v1alpha3.ClientTLSSettings
	5, // 3: dubbo.networking.v1alpha3.Subset.labels:type_name -> dubbo.networking.v1alpha3.Subset.LabelsEntry
	2, // 4: dubbo.networking.v1alpha3.Subset.traffic_policy:type_name -> dubbo.networking.v1alpha3.TrafficPolicy
	0, // 5: dubbo.networking.v1alpha3.ClientTLSSettings.mode:type_name -> dubbo.networking.v1alpha3.ClientTLSSettings.TLSmode
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_networking_v1alpha3_destination_rule_proto_init() }
func file_networking_v1alpha3_destination_rule_proto_init() {
	if File_networking_v1alpha3_destination_rule_proto != nil {
		return
	}
	file_networking_v1alpha3_virtual_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_destination_rule_proto_rawDesc), len(file_networking_v1alpha3_destination_rule_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_networking_v1alpha3_destination_rule_proto_goTypes,
		DependencyIndexes: file_networking_v1alpha3_destination_rule_proto_depIdxs,
		EnumInfos:         file_networking_v1alpha3_destination_rule_proto_enumTypes,
		MessageInfos:      file_networking_v1alpha3_destination_rule_proto_msgTypes,
	}.Build()
	File_networking_v1alpha3_destination_rule_proto = out.File
	file_networking_v1alpha3_destination_rule_proto_goTypes = nil
	file_networking_v1alpha3_destination_rule_proto_depIdxs = nil
}
