//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: networking/v1alpha3/virtual_service.proto

package v1alpha3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.dubbo.apache.org/v1alpha3
// +genclient
// +k8s:deepcopy-gen=true
// -->
type VirtualService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []string               `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Http          []*HTTPRoute           `protobuf:"bytes,2,rep,name=http,proto3" json:"http,omitempty"`
	ExportTo      []string               `protobuf:"bytes,3,rep,name=export_to,json=exportTo,proto3" json:"export_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualService) Reset() {
	*x = VirtualService{}
	mi := &file_networking_v1alpha3_virtual_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualService) ProtoMessage() {}

func (x *VirtualService) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_virtual_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualService.ProtoReflect.Descriptor instead.
func (*VirtualService) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_virtual_service_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualService) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *VirtualService) GetHttp() []*HTTPRoute {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *VirtualService) GetExportTo() []string {
	if x != nil {
		return x.ExportTo
	}
	return nil
}

type Destination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Subset        string                 `protobuf:"bytes,2,opt,name=subset,proto3" json:"subset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Destination) Reset() {
	*x = Destination{}
	mi := &file_networking_v1alpha3_virtual_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination) ProtoMessage() {}

func (x *Destination) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_virtual_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination.ProtoReflect.Descriptor instead.
func (*Destination) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_virtual_service_proto_rawDescGZIP(), []int{1}
}

func (x *Destination) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Destination) GetSubset() string {
	if x != nil {
		return x.Subset
	}
	return ""
}

type HTTPRoute struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Route         []*HTTPRouteDestination `protobuf:"bytes,1,rep,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRoute) Reset() {
	*x = HTTPRoute{}
	mi := &file_networking_v1alpha3_virtual_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRoute) ProtoMessage() {}

func (x *HTTPRoute) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_virtual_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRoute.ProtoReflect.Descriptor instead.
func (*HTTPRoute) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_virtual_service_proto_rawDescGZIP(), []int{2}
}

func (x *HTTPRoute) GetRoute() []*HTTPRouteDestination {
	if x != nil {
		return x.Route
	}
	return nil
}

type HTTPRouteDestination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   *Destination           `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRouteDestination) Reset() {
	*x = HTTPRouteDestination{}
	mi := &file_networking_v1alpha3_virtual_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRouteDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRouteDestination) ProtoMessage() {}

func (x *HTTPRouteDestination) ProtoReflect() protoreflect.Message {
	mi := &file_networking_v1alpha3_virtual_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRouteDestination.ProtoReflect.Descriptor instead.
func (*HTTPRouteDestination) Descriptor() ([]byte, []int) {
	return file_networking_v1alpha3_virtual_service_proto_rawDescGZIP(), []int{3}
}

func (x *HTTPRouteDestination) GetDestination() *Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *HTTPRouteDestination) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_networking_v1alpha3_virtual_service_proto protoreflect.FileDescriptor

const file_networking_v1alpha3_virtual_service_proto_rawDesc = "" +
	"\n" +
	")networking/v1alpha3/virtual_service.proto\x12\x19dubbo.networking.v1alpha3\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"}\n" +
	"\x0eVirtualService\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x128\n" +
	"\x04http\x18\x02 \x03(\v2$.dubbo.networking.v1alpha3.HTTPRouteR\x04http\x12\x1b\n" +
	"\texport_to\x18\x03 \x03(\tR\bexportTo\"?\n" +
	"\vDestination\x12\x18\n" +
	"\x04host\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04host\x12\x16\n" +
	"\x06subset\x18\x02 \x01(\tR\x06subset\"R\n" +
	"\tHTTPRoute\x12E\n" +
	"\x05route\x18\x01 \x03(\v2/.dubbo.networking.v1alpha3.HTTPRouteDestinationR\x05route\"~\n" +
	"\x14HTTPRouteDestination\x12N\n" +
	"\vdestination\x18\x01 \x01(\v2&.dubbo.networking.v1alpha3.DestinationB\x04\xe2A\x01\x02R\vdestination\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weightB\x1aZ\x18/api/networking/v1alpha3b\x06proto3"

var (
	file_networking_v1alpha3_virtual_service_proto_rawDescOnce sync.Once
	file_networking_v1alpha3_virtual_service_proto_rawDescData []byte
)

func file_networking_v1alpha3_virtual_service_proto_rawDescGZIP() []byte {
	file_networking_v1alpha3_virtual_service_proto_rawDescOnce.Do(func() {
		file_networking_v1alpha3_virtual_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_virtual_service_proto_rawDesc), len(file_networking_v1alpha3_virtual_service_proto_rawDesc)))
	})
	return file_networking_v1alpha3_virtual_service_proto_rawDescData
}

var file_networking_v1alpha3_virtual_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_networking_v1alpha3_virtual_service_proto_goTypes = []any{
	(*VirtualService)(nil),       // 0: dubbo.networking.v1alpha3.VirtualService
	(*Destination)(nil),          // 1: dubbo.networking.v1alpha3.Destination
	(*HTTPRoute)(nil),            // 2: dubbo.networking.v1alpha3.HTTPRoute
	(*HTTPRouteDestination)(nil), // 3: dubbo.networking.v1alpha3.HTTPRouteDestination
}
var file_networking_v1alpha3_virtual_service_proto_depIdxs = []int32{
	2, // 0: dubbo.networking.v1alpha3.VirtualService.http:type_name -> dubbo.networking.v1alpha3.HTTPRoute
	3, // 1: dubbo.networking.v1alpha3.HTTPRoute.route:type_name -> dubbo.networking.v1alpha3.HTTPRouteDestination
	1, // 2: dubbo.networking.v1alpha3.HTTPRouteDestination.destination:type_name -> dubbo.networking.v1alpha3.Destination
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_networking_v1alpha3_virtual_service_proto_init() }
func file_networking_v1alpha3_virtual_service_proto_init() {
	if File_networking_v1alpha3_virtual_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networking_v1alpha3_virtual_service_proto_rawDesc), len(file_networking_v1alpha3_virtual_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_networking_v1alpha3_virtual_service_proto_goTypes,
		DependencyIndexes: file_networking_v1alpha3_virtual_service_proto_depIdxs,
		MessageInfos:      file_networking_v1alpha3_virtual_service_proto_msgTypes,
	}.Build()
	File_networking_v1alpha3_virtual_service_proto = out.File
	file_networking_v1alpha3_virtual_service_proto_goTypes = nil
	file_networking_v1alpha3_virtual_service_proto_depIdxs = nil
}
